- README.md
Updating Meeting Time in README.md
> Updating Meeting Time in README.md

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Adding issue templates for creating a bug report and a feature request.
> Adding Issue Templates

- .gitignore
- Dockerfile
- README.md
- composer.json
- phpunit.xml.dist
- resources/test-using-docker
- src/Exporter.php
- src/Exporter/BasisExporter.php
- src/Exporter/ZipkinExporter.php
- src/Tracing/Builder.php
- src/Tracing/Event.php
- src/Tracing/Span.php
- src/Tracing/SpanContext.php
- src/Tracing/Status.php
- src/Tracing/Tracer.php
- src/Transport.php
- src/Transport/TarantoolQueueTransport.php
- tests/TracingTest.php
@bobstrecansky please review current code state
> initial commit

- README.md
- src/Exporter/BasisExporter.php
- src/Exporter/ZipkinExporter.php
- src/Tracing/Builder.php
- src/Tracing/Event.php
- src/Tracing/Span.php
- src/Tracing/SpanContext.php
- src/Tracing/Status.php
- src/Tracing/Tracer.php
- tests/TracingTest.php
This is a partial improvement to the implementation based on a reading of the spec between Levi Morrison and Bob Strecansky.
> Refactor initial implementation

- src/Internal/Clock.php
- src/Trace/SpanProcessor/BatchSpanProcessor.php
- tests/unit/Trace/SpanProcessor/BatchSpanProcessorTest.php
I added BatchSpanProcessor.
In the specs it says that BatchSpanProcessor should have an exporterTimeout param. I added this param, but for now has no efect since our exporters does not support for timeout param.
Also I added a new Clock class to simplify testing of the BatchSpanProcessor.
> Batch span processor

- src/Context/SpanContext.php
- tests/Context/SpanContextTest.php
Implements the SpanContext up to specifications: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#spancontext
> Clean up and finish the SpanContext

- src/Trace/Status.php
- tests/Trace/StatusTest.php
- tests/integration/TracingTest.php
Code cleanup on the `Trace\Status` class.
> Clean up Trace\Status

- tests/Trace/StatusTest.php
Attempting to fix CI for the time being using php-cs-fixer
> Fixing PHP for CI using php-cs-fixer

- composer.json
> Bump missed PHP version requirement

- Makefile
- README.md
- docker-compose.yaml
- examples/AlwaysOffTraceExample.php
- examples/JaegerExporterExample.php
- phpunit.xml.dist
- sdk/Tests/TracingTest.php
- sdk/Trace/JaegerExporter.php
- sdk/Trace/Tracer.php
- sdk/Trace/Zipkin/SpanConverter.php
- sdk/Trace/ZipkinExporter.php
- tests/unit/Exporter/JaegerExporterTest.php
- tests/unit/Exporter/ZipkinExporterTest.php
- tests/unit/Exporter/ZipkinSpanConverterTest.php
Added new exporter for Jaeger using Zipkin like HTTP protocol.
> Jaeger exporter

- CODEOWNERS
Creating a CODEOWNERS file for this repo.
> Adding Codeowners

- sdk/Tests/AlwaysOffSamplerTest.php
- sdk/Tests/AlwaysOnSamplerTest.php
- sdk/Tests/AlwaysParentSamplerTest.php
- sdk/Tests/ProbabilitySamplerTest.php
- sdk/Trace/AlwaysOffSampler.php
- sdk/Trace/AlwaysOnSampler.php
- sdk/Trace/AlwaysParentSampler.php
- sdk/Trace/ProbabilitySampler.php
- sdk/Trace/Sampler.php
- sdk/Trace/Span.php
Added a `SpanKind` property to `Span` class.
Add `SpanKind` as an argument in `Sampler::shouldSample()`.
> Implement API\SpanKind

- examples/AlwaysOffTraceExample.php
- examples/AlwaysOnTraceExample.php
- examples/JaegerExporterExample.php
While doing some investigation on adding the right timestamp stuff; I noticed that when the SpanKind methods were added, the examples were never updated to reflect that.  This PR adds these back in so the examples work.
cc\ @lalex
> Update Examples with SpanKind

- README.md
Adding some updates to the README.md for new contributors to get up to speed more quickly.
> Adding more information to README.md

- sdk/Trace/Span.php
- tests/Sdk/Unit/Trace/TracingTest.php
* This adds the missing test for setAttribute() while recording
* But also adds the isRecoding logic check for other trace events that
should not be modified when isRecoding is false
* And adds tests for these other modifications as well
> testing around $span->isRecording()

- api/Trace/Span.php
- api/Trace/SpanContext.php
- sdk/Trace/Span.php
- sdk/Trace/SpanProcessor/BatchSpanProcessor.php
- sdk/Trace/SpanProcessor/SimpleSpanProcessor.php
- tests/Sdk/Unit/Trace/SpanProcessor/BatchSpanProcessorTest.php
- tests/Sdk/Unit/Trace/SpanProcessor/SimpleSpanProcessorTest.php
Recreating this due to CLA 
https://github.com/open-telemetry/opentelemetry-php/issues/140
> Only sampled spans should be exported

- api/Trace/SpanKind.php
- sdk/Trace/SpanOptions.php
- tests/Sdk/Unit/Trace/SpanOptionsTest.php
> Added setSpanKind implementation and a test for it

- contrib/Zipkin/SpanConverter.php
- tests/Contrib/Unit/ZipkinSpanConverterTest.php
* Opentelemetry attributes allow strings, booleans, numbers and arrays of each.
* Opentelemetry attributes map to Zipkin tags, which must be pairs of strings.
* This change maps attribute values onto tag values, converting booleans to 'true' or 'false' strings, and converting arrays to comma separated strings with each array member sanitised.
* *NOTE*: `OpenTelemetry\Trace\Span` does not currently handle attribute values containing arrays fully and does not verify that arrays contain only one value type; This is part of the spec. This change assumes that the `Span` is responsible for initial typechecking of the passed in values.
> Coerce span attrs to strings for zipkin export

- sdk/Trace/SpanContext.php
- sdk/Trace/Tracer.php
- tests/Sdk/Unit/Support/HasTraceProvider.php
- tests/Sdk/Unit/Trace/SpanContextTest.php
- tests/Sdk/Unit/Trace/SpanOptionsTest.php
> Added parameter $sapmled in SpanContext generate method

- README.md
This PR closes issue #176 by updating the zoom link in the README
> Update readme zoom link

- CONTRIBUTING.md
This PR adds @jodeev as a Triager.
> Add Jodee Varney as a Triager

- Makefile
- examples/AlwaysOnJaegerExample.php
- examples/AlwaysOnZipkinExample.php
make file updates to reflect changes
fixes #189
> rename zipkin and jaegar example tracing  as appropriate

- Makefile
- README.md
> rename make examples to make tracing examples

- .github/workflows/php.yml
- Context/Context.php
- Makefile
- composer.json
- phpstan.neon
Fixes issues #196 
Hello @dkarlovi @bobstrecansky any input on this?
> add phpstan static analysis tool

- README.md
Note about our initial release for the README.md
> Initial Release Note

- sdk/Trace/NoopSpan.php
- sdk/Trace/Span.php
- sdk/Trace/SpanOptions.php
- sdk/Trace/Tracer.php
- sdk/Trace/TracerProvider.php
- tests/Sdk/Unit/Trace/TracerProviderTest.php
- tests/Sdk/Unit/Trace/TracingTest.php
Implement the sampler into the tracer and trace provider.
> Implement the sampler into the tracer and trace provider.

- contrib/Zipkin/Exporter.php
- contrib/Zipkin/SpanConverter.php
- phpstan.neon.dist
- psalm.xml.dist
- sdk/CorrelationContext.php
- sdk/Metrics/Meter.php
- sdk/Resource/ResourceInfo.php
- sdk/Trace/Events.php
- sdk/Trace/SpanProcessor/BatchSpanProcessor.php
This adds fixes which are required to bump static analysis tools to stricter settings, revealing some bugs already.
> fix: bump PHPStan to level 5, Psalm to level 3

- .github/workflows/php.yml
- .phan/config.php
- composer.json
- contrib/Otlp/Exporter.php
- contrib/Zipkin/Exporter.php
- docker/Dockerfile
Making the changes necessary to be PHP 8.0 compatible.  Comments in line.
> PHP 8 Compatiblity trial - adding PHP 8.0

- sdk/Trace/TracerProvider.php
- tests/Sdk/Unit/Trace/TracerProviderTest.php
This PR addresses https://github.com/open-telemetry/opentelemetry-php/issues/241
> TraceProvider lookups tracers only by name, instead of name and version

- sdk/Trace/TracerProvider.php
- tests/Sdk/Unit/Trace/TracingTest.php
@wRLSS 's [PR](https://github.com/open-telemetry/opentelemetry-php/pull/248) had a slight style error, but it was not caught in CI because we were waiting for the [github master / main action PR](https://github.com/open-telemetry/opentelemetry-php/pull/245) to be fixed.  This PR fixes up the one styling error that came about so that the CI passes.
> Fixing Style from PR

- sdk/Trace/IdGenerator.php
- sdk/Trace/RandomIdGenerator.php
- sdk/Trace/TracerProvider.php
- tests/Sdk/Integration/Context/SpanContextTest.php
- tests/Sdk/Unit/Trace/RandomIdGeneratorTest.php
Add SDK IdGenerator interface and default RandomIdGenerator implementation.
Spec: https://github.com/open-telemetry/opentelemetry-specification/blob/03a6f0fd9d1d2f5e08858b102ba620ebf3e4a6fa/specification/trace/sdk.md#id-generators
> Add IdGenerator interface

- README.md
Fixes issue #261 
Update communications link to Slack CNCF
> Update communications link to slack

- api/CorrelationContext.php
> Update  namespace for CorrelationContext class

- user-integration-guide/symfony-integration.md
This fixes #263 
Super thanks to @dkarlovi  for the [Symfony integration example](https://github.com/dkarlovi/opentelemetry-php-user-test)
> WIP/Add OpenTelemetry PHP Symfony integration guide

- .github/workflows/docs-update.yml
This GitHub action will automatically create a PR in the opentelemetry.io repository when a new release is published (it also allows you to push an update manually).
> Add documentation update action

- contrib/Otlp/Exporter.php
Fix #313: wrong variable in Otlp Exporter
> Fix #313: wrong variable in Otlp Exporter

- sdk/Trace/Tracer.php
> Use IdGenerator to generate trace ids instead of randomHex

- README.md
> Add PHPStan command to PR guide

- CODEOWNERS
I've just been too busy for too long
> Remove morrisonlevi as code owner

- docs/laravel-integration.md
Update Laravel integration guide to meet V.0.0.2 requirements.
This fixes #350
> Update laravel guide for v.0.0.2

- api/Trace/Tracer.php
- docs/laravel-integration.md
- docs/symfony-integration.md
- examples/AlwaysOnJaegerExample.php
- examples/AlwaysOnNewrelicExample.php
- examples/AlwaysOnOTLPExample.php
- examples/AlwaysOnOTLPGrpcExample.php
- examples/AlwaysOnOTLPGrpcExample1.php
- examples/AlwaysOnZipkinExample.php
- examples/AlwaysOnZipkinToNewrelicExample.php
- sdk/Trace/Tracer.php
- tests/Sdk/Unit/Trace/TracerTest.php
- tests/TraceContext/W3CTestService/TestController.php
- tests/TraceContext/W3CTestService/index.php
> Remove Tracer::endActiveSpan()

- contrib/OtlpGrpc/Exporter.php
- tests/Contrib/Unit/OTLPGrpcExporterTest.php
The following fixes a parsing bug in the metadataFromHeader code. I've added some tests as well.
Fixes #366
> fix metadataFromHeaders parsing bug

- docker/Dockerfile
minor change but makes the file more readable.
> fix dockerfile spacing

- sdk/Resource/ResourceConstants.php
This is a short two line PR adds two resource constants that conform to the specifications seen here:
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/container.md
> New resource constants

- .github/workflows/php.yml
> Add GHAction Command 

- CODEOWNERS
I won't be able to contribute effectively for a while.
> Remove Fahmy as an approver

- Makefile
- contrib/OtlpGrpc/Exporter.php
- docker-compose-collector.yaml
- tests/Contrib/Unit/OTLPGrpcExporterTest.php
- tests/Contrib/Unit/OTLPHttpExporterTest.php
This reverts commit 8e6487450933e549736b9fb3e03733de0db4807b.
https://github.com/open-telemetry/opentelemetry-php/pull/398#issuecomment-899604418
> Revert "change OTLP/HTTP port (#389) (#398)"

- src/Context/Propagation/ArrayAccessGetterSetter.php
- src/Context/Propagation/KeyedArrayAccessInterface.php
- tests/Context/Unit/Propagation/ArrayAccessGetterSetterTest.php
Fixes 2 issues from https://github.com/open-telemetry/opentelemetry-php/issues/464
> Move KeyedArrayAccessInterface to Context

- tests/API/Unit/Trace/SpanContextTest.php
This is a left-over from https://github.com/open-telemetry/opentelemetry-php/pull/467
> Move SpanContextTest to API

- composer.json
- src/Contrib/Jaeger/Exporter.php
- src/Contrib/Newrelic/Exporter.php
- src/Contrib/OtlpHttp/Exporter.php
- src/Contrib/Zipkin/Exporter.php
- src/Contrib/ZipkinToNewrelic/Exporter.php
- tests/SDK/Unit/Trace/ExporterFactoryTest.php
closes: https://github.com/open-telemetry/opentelemetry-php/issues/448
(Still working on the other exporter issues. This is simply fixing the Guzzle issues for now)
> Fix Exporters` fromConnectionString method

- Makefile
- README.md
- adding 'make all', which runs the important parts of CI process
- ensuring xdebug mode is set correctly for make targets
> Makefile updates

- examples/ConfigurationFromEnvironment.php
- examples/distributed-tracing/docker-compose.yml
- src/SDK/Trace/SpanProcessorFactory.php
- tests/SDK/Unit/Trace/SpanProcessorFactoryTest.php
see https://github.com/open-telemetry/opentelemetry-specification/pull/2172#issuecomment-982312473
> switching span processor selection to language-specific

- README.md
Adds installation requirements to README
see: https://github.com/open-telemetry/opentelemetry-php/issues/481
> Add installation requirements to README

- README.md
There has been a formatting error in: https://github.com/open-telemetry/opentelemetry-php/pull/510
> Fix formatting in REAME

- examples/AlwaysOnJaegerExample.php
> fixing jaeger example

- .gitignore
- Makefile
- README.md
- composer.json
- phpmetrics.json
This PR adds a make target to create a PhpMetrics  report of the library
> Add PhpMetrics reporting

- website_docs/_index.md
- website_docs/getting-started.md
- Contributes https://github.com/open-telemetry/opentelemetry.io/issues/1096
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/780
/cc @cartermp @austinlparker
> [website_docs] Fix page meta links and rename file

- .github/stale.yml
In our sig meeting today, we discussed adding a stalebot setup.  This PR does exactly that!
> Stalebot setup

- src/Contrib/Jaeger/SpanConverter.php
- src/Contrib/Newrelic/SpanConverter.php
- src/Contrib/Zipkin/SpanConverter.php
- src/Contrib/ZipkinToNewrelic/SpanConverter.php
- tests/Unit/Contrib/JaegerSpanConverterTest.php
- tests/Unit/Contrib/NewrelicSpanConverterTest.php
- tests/Unit/Contrib/ZipkinSpanConverterTest.php
- tests/Unit/Contrib/ZipkinToNewrelicSpanConverterTest.php
PR for issue #225. Updated SpanConverters to export ResourceInfo attributes.
> Exporting ResourceInfo in SpanConverter

- src/SDK/Resource/Detectors/Environment.php
- tests/Unit/SDK/Common/Environment/EnvironmentVariablesTraitTest.php
Refactored Environment.php to use EnvironmentVariablesTrait::hasEnvironmentVariable function instead of Resolver::hasVariable.
> Refactored Environment.php

- src/SDK/Trace/ExporterFactory.php
- src/SDK/Trace/SamplerFactory.php
- src/SDK/Trace/SpanProcessorFactory.php
Replaced hard coded values with known values in ExporterFactory, SamplerFactory, SpanProcessorFactory
> Refactoring to use known values

- CONTRIBUTING.md
Updated CONTRIBUTING.md by adding a section of members and a section for people who already contributed.
> Updated Members and Contributors

- src/SDK/Common/Environment/Resolver.php
- tests/Unit/SDK/Common/Environment/ResolverTest.php
closes: https://github.com/open-telemetry/opentelemetry-php/issues/613
> Support resolution of Environment Variables set by  DotEnv libraries

- depfile.yaml
Update `depfile.yaml` to cover newly introduced dependencies.
> Update dependency checks 

- examples/ParentSpanExample.php
- examples/SpanResources.php
- src/SDK/Resource/Detectors/Composer.php
- src/SDK/Resource/Detectors/Composite.php
- src/SDK/Resource/ResourceInfo.php
- src/SDK/Resource/ResourceInfoFactory.php
- src/SDK/Trace/TracerProvider.php
- tests/Unit/SDK/Resource/ResourceTest.php
- tests/Unit/SDK/Trace/SpanTest.php
- tests/Unit/SDK/Util/SpanData.php
Created ResourceInfoFactory class and moved merge, defaultResource, and emptyResource methods from ResourceInfo to ResourceInfoFactory.
Fixes #621.
> Created ResouceInfoFactory class

- .github/config.yml
welcome-bot has been installed in our repo, this is config to make it do something on a first PR
fixes #552
> adding new contributor welcome message

- .github/workflows/php.yml
- .phan/config.php
- Makefile
- composer.json
- Adds https://github.com/opentelemetry-php/dev-tools as a dev dependency
- Calls package composer validation in CI
- Adds make target for package composer validation
> Add validation for package composer files

- README.md
closes: https://github.com/open-telemetry/opentelemetry-php/issues/507
> Add package information to README

- DEVELOPMENT.md
- README.md
> Move development information from the main README into a dedicated DEVELOPMENT.md 

- README.md
closes: https://github.com/open-telemetry/opentelemetry-php/issues/728
> Add link to development doc in to main README

- README.md
Added extension packages search link on packagist.
> Update README to include extension packages

- README.md
Updated README to add project status table. Replaces #785.
> Added project status table in README

- src/SDK/Common/Attribute/FilteredAttributesBuilder.php
- src/SDK/Common/Attribute/FilteredAttributesFactory.php
- src/SDK/Trace/SpanLimitsBuilder.php
- tests/Integration/SDK/SpanLimitsBuilderTest.php
- tests/Integration/SDK/TracerTest.php
- tests/Unit/SDK/Common/Attribute/FilteredAttributesTest.php
- tests/Unit/SDK/Trace/SpanLimitsBuilderTest.php
> Drop general identity attributes by default

- README.md
https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification#project-naming
> Align project names

- examples/metrics/features/exporters/otlp_grpc.php
OTLP GRPC example has a call to an unknown method.
> Fix OTLP GRPC example

- CONTRIBUTING.md
adding pdelewski, our newest maintainer
moving some past members into a new 'emeritus' section
> updating membership lists

- composer.json
- src/API/Baggage/Baggage.php
- src/API/Trace/TraceState.php
use latest version, and apply suggested updates
> upgrade rector

- src/SDK/Resource/Detectors/Container.php
We should check whether file exists
```
1) OpenTelemetry\Tests\Instrumentation\Laravel\tests\Integration\LaravelInstrumentationTest::test_http_kernel_handle
file_get_contents(/proc/self/mountinfo): Failed to open stream: No such file or directory
/Users/pdelewski/Projects/!/opentelemetry-php-contrib/src/Instrumentation/Laravel/vendor/open-telemetry/sdk/Resource/Detectors/Container.php:62
```
> open stream failure

- README.md
- src/SDK/Common/Configuration/KnownValues.php
- src/SDK/Resource/ResourceInfoFactory.php
- tests/Integration/SDK/ResourceInfoFactoryTest.php
- tests/Unit/SDK/Resource/ResourceInfoFactoryTest.php
- add composer to defaults
- update readme: missing info about container & composer
> Resource detector

- rector.php
- src/Contrib/Otlp/AttributesConverter.php
Latest rector update adds some new rules. Apply one new rule, and disable FlipTypeControlToUseExclusiveTypeRector (which changes about 40 files, and IMO makes it harder to comprehend)
> new rector rules

- src/Contrib/Otlp/LogsConverter.php
- src/Contrib/Otlp/LogsExporter.php
- src/Contrib/Otlp/MetricConverter.php
- src/Contrib/Otlp/MetricExporter.php
- src/Contrib/Otlp/ProtobufSerializer.php
- src/Contrib/Otlp/SpanConverter.php
- src/Contrib/Otlp/SpanExporter.php
- tests/Unit/Contrib/Otlp/SpanExporterTest.php
Fixes #969, alternative to #971; uses the approach mentioned in https://github.com/open-telemetry/opentelemetry-php/pull/971#issuecomment-1509849033.
> Fix otlp json trace id and span id

- proto/otel/composer.json
- src/API/composer.json
- src/Context/composer.json
- src/Contrib/Grpc/composer.json
- src/Contrib/Newrelic/composer.json
- src/Contrib/Otlp/composer.json
- src/Contrib/Zipkin/composer.json
- src/Contrib/ZipkinToNewrelic/composer.json
- src/Extension/Propagator/B3/composer.json
- src/SDK/composer.json
- src/SemConv/composer.json
Simplifies installation of unreleased changes.
> Add branch aliases

- src/SDK/Common/Configuration/Defaults.php
- src/SDK/Common/Configuration/ValueTypes.php
- src/SDK/Common/Configuration/Variables.php
- src/SDK/Logs/LogRecordProcessorFactory.php
- src/SDK/Logs/Processor/BatchLogsProcessor.php
- tests/Unit/SDK/Logs/LogRecordProcessorFactoryTest.php
Adding new spec variables for configuring batch LogRecord processor from environment.
> adding batch LogRecord processor env config

- src/API/Trace/Propagation/TraceContextPropagator.php
- src/API/Trace/SpanContext.php
- src/API/Trace/SpanContextInterface.php
- src/API/Trace/TraceFlags.php
- src/Extension/Propagator/B3/B3MultiPropagator.php
- src/Extension/Propagator/B3/B3SinglePropagator.php
- src/SDK/Trace/SpanBuilder.php
- tests/Integration/SDK/AlwaysOffSamplerTest.php
- tests/Integration/SDK/AlwaysOnSamplerTest.php
- tests/Integration/SDK/Context/SpanContextTest.php
- tests/Integration/SDK/ParentBasedTest.php
- tests/Integration/SDK/SpanBuilderTest.php
- tests/Integration/SDK/TraceIdRatioBasedSamplerTest.php
- tests/Integration/SDK/TracerTest.php
- tests/Unit/API/Trace/Propagation/TraceContextPropagatorTest.php
- tests/Unit/API/Trace/SpanContextTest.php
- tests/Unit/Extension/Propagator/B3/B3MultiPropagatorTest.php
- tests/Unit/Extension/Propagator/B3/B3PropagatorTest.php
- tests/Unit/Extension/Propagator/B3/B3SinglePropagatorTest.php
- tests/Unit/SDK/Metrics/Exemplar/FilteredReservoirTest.php
- tests/Unit/SDK/Trace/NonRecordingSpanTest.php
- tests/Unit/SDK/Trace/Sampler/ParentBasedTest.php
- tests/Unit/SDK/Trace/SpanProcessor/SimpleSpanProcessorTest.php
> move trace flags consts into TraceFlags interface

- src/Contrib/Otlp/HttpEndpointResolver.php
- src/Contrib/Otlp/HttpEndpointResolverInterface.php
- src/Contrib/Otlp/LogsExporterFactory.php
- src/Contrib/Otlp/MetricExporterFactory.php
- src/Contrib/Otlp/SpanExporterFactory.php
- tests/Unit/Contrib/Otlp/HttpEndpointResolverTest.php
otlp exporter code belongs in contrib/otlp
> moving some otlp code out of sdk

- src/SDK/composer.json
adding some links to try to make it easier for users to find the right support/repositories etc.
just doing one composer file to see if it works, and will follow-up with more in a later PR
> adding support info to sdk composer

- examples/logs/features/batch_exporting.php
- src/SDK/Logs/Exporter/ConsoleExporter.php
support multiple scopes in console log output, and update batch example to illustrate
> improve logs console output

- examples/logs/exporters/otlp_http.php
- src/Contrib/Otlp/LogsConverter.php
> set schemaUrl for logs output

- src/Contrib/Otlp/OtlpHttpTransportFactory.php
> OtlpHttpTransportFactory should pass all arguments to PsrTransportFactory

- src/SDK/Common/Export/Http/PsrTransport.php
- tests/Unit/SDK/Common/Export/Http/PsrTransportTest.php
> Fix for maxRetries=0

- examples/disabling_sdk.php
- examples/traces/features/configuration_from_environment.php
- examples/traces/features/span_resources.php
- src/Contrib/Otlp/MetricExporter.php
- src/SDK/Common/Configuration/Defaults.php
- src/SDK/Common/Configuration/KnownValues.php
- src/SDK/Common/Configuration/ValueTypes.php
- src/SDK/Common/Configuration/Variables.php
- src/SDK/Logs/LogRecordLimitsBuilder.php
- src/SDK/Resource/Detectors/SdkProvided.php
- src/SDK/SdkAutoloader.php
- src/SDK/Trace/SamplerInterface.php
- src/SDK/Trace/SpanLimitsBuilder.php
I noticed that some of the repository links are outdated.
Can you review this fix?
> fix: documentations links

- src/SDK/SdkAutoloader.php
- tests/Unit/SDK/SdkAutoloaderTest.php
improve code and add more tests to the OTEL_PHP_EXCLUDED_URLS feature
> improve excluded urls code

- .github/workflows/publish-otel-php-base-docker-image.yml
this should resolve some deprecation warnings for some things that will soon break
> update image build actions to latest versions

- DEVELOPMENT.md
I think the original site might have expired 👀 
Updated per https://github.com/flemay/3musketeers:
> Updated link to 3musketeers site.

- src/API/Baggage/BaggageBuilder.php
- src/API/Baggage/BaggageBuilderInterface.php
- src/API/Logs/EventLoggerInterface.php
- src/API/Logs/LogRecord.php
- src/API/Trace/NonRecordingSpan.php
- src/API/Trace/SpanInterface.php
- src/Context/Propagation/MultiTextMapPropagator.php
- src/Contrib/Zipkin/Exporter.php
- src/SDK/Common/Dev/Compatibility/Util.php
- src/SDK/Logs/EventLogger.php
- src/SDK/Logs/LoggerProvider.php
- src/SDK/Metrics/MeterProvider.php
- src/SDK/Trace/Span.php
- src/SDK/Trace/TracerProvider.php
php8.4 deprecates implicit null (now checked by phan)
> fix implicit null usage

- src/SDK/Common/Http/Psr/Client/Discovery/Guzzle.php
> fix: Guzzle version 6 error in Http Client Discovery

- .github/workflows/php.yml
- build against 8.5 (nightly)
- make 8.4 non-experimental
> adding php 8.5 to build matrix

- .github/workflows/php.yml
psalm is not yet compatible with 8.4, so force it
> ignore platform reqs for 8.4 install

- src/SDK/Common/Attribute/AttributesBuilder.php
this is already implemented for logs and traces as required by spec
> remove todo for logging dropped attributes

- src/Contrib/Grpc/GrpcTransportFactory.php
- tests/Unit/Contrib/Grpc/GrpcTransportFactoryTest.php
> Check max retry on grpc transport

- .github/workflows/publish-otel-php-base-docker-image.yml
Add an image for 8.4 as well :)
> chore: publish base image for 8.4 as well

- src/Contrib/Otlp/ProtobufSerializer.php
Resolves #978, `PrintOptions` is available in `^4.31`.
> Use protobuf `PrintOptions` if available

- src/Config/SDK/ComponentProvider/InstrumentationConfigurationRegistry.php
- tests/Unit/SDK/fixtures/otel-sdk.yaml
See [schema/opentelemetry_configuration.json](https://github.com/open-telemetry/opentelemetry-configuration/blob/f27ee13bbc7ee8156954aea79b1d8bfb0312b7cc/schema/opentelemetry_configuration.json#L35).
> Mark `.instrumentation` as experimental

- docker/Dockerfile
chore: Made the update from https://github.com/open-telemetry/opentelemetry-php/pull/1624 strictly for PHP 8.4
> Update Dockerfile for latest PHP 8.4

- CONTRIBUTING.md
Related to https://github.com/open-telemetry/community/issues/2830
> Update community member listings

- examples/src/_register.php
- phpstan.neon.dist
- src/Config/SDK/ComponentProvider/Propagator/TextMapPropagatorCloudTrace.php
- src/Config/SDK/_register.php
- src/SDK/Logs/LogRecordProcessorInterface.php
- src/SDK/Logs/Logger.php
- src/SDK/Logs/Processor/BatchLogRecordProcessor.php
- src/SDK/Logs/Processor/MultiLogRecordProcessor.php
- src/SDK/Logs/Processor/NoopLogRecordProcessor.php
- src/SDK/Logs/Processor/SimpleLogRecordProcessor.php
- tests/Integration/SDK/Logs/LoggerTest.php
- tests/Unit/SDK/Logs/LoggerTest.php
Related: https://github.com/open-telemetry/opentelemetry-php/issues/1626
> adding LogRecordProcessor.enabled
