open-telemetry/opentelemetry-php

.gitignore, src/Exporter.php, src/Exporter/ZipkinExporter.php
The covers issue #22
The opentelemetry spec requires the exporter to be implemented as an interface with two methods: export & shutdown. This is a simple change to refactor what was the Exporter class to an Exporter interface, and update what we have of the zipkin exporter class.
There's more work that needs to be done to consider this finalized, but it may need to be done in parallel with a functioning export class that implements it.
=> Change exporter to interface and update exporters to implement - WIP

src/Exporter.php, src/Exporter/ZipkinExporter.php
This uses an `iterable` of `Span` instead of a variadic. This allows for implementers to use `SplFixedArray` or some other custom type instead of forcing them to use PHP's arrays.
Removes `shutdown`. The semantics of `shutdown()` are equivalent to a destructor, aside from this bit:
> After the call to Shutdown subsequent calls to Export are not allowed and should return FailedNotRetryable error.
I see no point. If it's done, it's done, don't try to call it.
=> Clean up Exporter and ZipkinExporter

.gitignore, composer.lock
Can we add composer.lock in the repository? We all should work with same versions of phan, phpunit, etc.
Earlier today I installed the library on my computer where php 7.3 was installed, and latter when I wanted to check the code using `./resources/phan-using-docker`, which is using php 7.1, it crashed because depencies with higher versions(for php 7.3) were installed, during composer install.
I know that composer ignores composer.lock files from libraries when those are included in a bigger project, so it shouldn't be a problem for other users that includes this library in their projects.
=> add composer.lock

.dockerignore, composer.json, resources/Dockerfile.phan, resources/Dockerfile.test, src/Exporter/BasisExporter.php, src/Exporter/ExporterInterface.php, src/Exporter/ZipkinExporter.php, src/SpanProcessorInterface.php, src/Tracing/Sampler/AlwaysOffSampler.php, src/Tracing/Sampler/AlwaysOnSampler.php, src/Tracing/Sampler/SamplerInterface.php, src/Tracing/Span.php, src/Tracing/SpanContext.php, src/TransportInterface.php, tests/TracingTest.php, tests/unit/Tracing/Sampler/AlwaysOffSamplerTest.php, tests/unit/Tracing/Sampler/AlwaysOnSamplerTest.php
- moved Export interface to Exporter directory and renamed it from Exporter to ExporterInterface because I think that interfaces should be in the same directory with the implementations
- rename Transport interface into TransportInterface. I think that interface classes should have Interface prefix
- added SpanProcessorInterface as described in specifications
- improved tests autoloading in order to avoid importing require '/../../../../vendor/autoload.php' in every test file
=> interfaces improvements

.travis.yml
At least so far we've officially been supporting PHP 7.1+, so it makes sense to run tests for PHP 7.1.
=> Run PHP 7.1 in Travis CI

Makefile
This doesn't remove the lines originating from XdebugHandler, e.g.
```
[debug] Checking PHAN_ALLOW_XDEBUG
[debug] Because xdebug was installed, Phan will restart.
[debug] The Xdebug extension is loaded (2.9.1)
[debug] Process restarting (PHAN_ALLOW_XDEBUG=internal|2.9.1|1|*|*)
[debug] Running '/usr/local/bin/php' '-n' '-c' '/tmp/LPtCmV' './vendor/bin/phan'
```
=> Suppresses warnings from Phan about Xdebug

docker/Dockerfile
This warning will become an error in a future release
```bash
[WARNING]: Empty continuation line found in:
RUN apt-get -y update && apt-get -y install git zip && curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer && chmod +x /usr/local/bin/composer && pecl install ast-1.0.4 xdebug && docker-php-ext-enable ast xdebug
[WARNING]: Empty continuation lines will become errors in a future release.
```
=> Removes Dockerfile warning for continuation line

docker/Dockerfile
This extension speeds up the `make phan` step on multi-processor systems
Before:
```
-> % time make phan
make phan  0.49s user 0.09s system 4% cpu 13.460 total
```
After:
```
-> % time make phan
make phan  0.53s user 0.11s system 13% cpu 4.733 total
```
=> Require the pcntl extension for development

.travis.yml, .travis/xdebug.sh
Only enables XDebug when running PHPUnit. This should speed up PHP tasks like Phan and in some cases Composer if Travis doesn't optimize for that.
=> Disable XDebug on CI

README.md, examples/AlwaysOffTraceExample.php, examples/AlwaysOnTraceExample.php
I tried giving the sample code a try and ran into a "non-static method called statically" error and a type error trying to pass a non-string to the `md5` function.  This PR fixes these PHP errors, and also fixes the link to the sample program from the README.md
=> Fixes Broken Example Code and Link in README

README.md
This commit fixes a wrong link in the readme.
=> Wrong example link

.travis.yml, docker/Dockerfile, src/Trace/TracerFactory.php
PHP 7.1 has been EoL'ed, and doesn't have security support anymore.  I've removed it from CI and moved our default Dockerfile to use PHP7.2.  
I've also added in testing for PHP7.4, as php 7.4.2 is the current stable PHP version.
=> Remove PHP 7.1, add PHP 7.4

sdk/Internal/Clock.php, sdk/Tests/InternalClockTest.php
This PR fixes a bug when some digits for milliseconds were missing due to transformation between floats and strings.
ex.
microtime: 0.00116800 1586110291
expected: 1586110291001.168
actual result:  1586110291168
=> internal clock milliseconds fix

api/Trace/Attribute.php, sdk/Trace/Attribute.php
@beniamin mentioned that we should add explicit references for attribute iterables.  I performed this action for the api and sdk trace attribute `getValue` functions; we should discuss whether or not there are other places where we would like to do this.
=> Adding Explicit Reference for Attribute Iterables

README.md
Hi all,
While the title is pretty self explanatory, the link to `examples/AlwaysOnTraceExample.php` is broken in the README. This commit corrects the relative path to always be correct for a given fork/branch.
Thanks!
=> Correct relative link to example in README

CONTRIBUTING.md
Creating this list in order to decentralize our Maintainers and Approvers list.  Following patterns of other [sigs](https://github.com/open-telemetry/opentelemetry-python/pull/268/files); I think this is correct.
=> Adding a CONTRIBUTING.md file to the repo

.travis.yml, .travis/phpcs.sh
This PR accomplishes 2 things:
* Updates the version we test with from Trusty (16.04) to Bionic (18.04).  Trusty is out of standard support, so I figured it was best to move to the next version.
* Moves the travis phpcs test from within the `.travis.yml` file to its own separate script in `.travis/phpcs.sh`.  This makes the [output from CI](https://travis-ci.org/github/open-telemetry/opentelemetry-php/jobs/694432862#L504-L509) a little easier to read and grok.
=> Phpcs fix in shell script

code-of-conduct.md
Adding a code of conduct for reference, which mirrors OpenTelemetry's Code of Conduct, which mirrors the CNCF code of conduct.
=> Adding Code of Conduct

composer.json, sdk/Resource/ResourceConstants.php, sdk/Resource/ResourceInfo.php, sdk/Trace/InstrumentationLibrary.php, sdk/Trace/Tracer.php, sdk/Trace/TracerProvider.php, tests/unit/Resource/ResourceTest.php, tests/unit/Trace/TracingTest.php
This is an implementation of `Resource` SDK (#92) and recently added `InstrumentationLibrary` ([TracerCreation](https://github.com/open-telemetry/opentelemetry-specification/blob/1a0395e482d4fec6faab0ee4b7bc1dc5fdd3e493/specification/trace/sdk.md#tracer-creation)).
In this PR minimal changes were made to `TracerProvider` and `Tracer` to simplify a merge with the concurrent PRs.
The class for `Resource` is called `ResourceInfo` because `resource` is the reserved word in PHP and it makes difficulties for code analysis tools. Any suggestion on name are welcome.
In specification `Resource` is proposed as immutable object. Now it is not fully immutable since it uses `Attributes` collection which is mutable.
=> Add Resource SDK

sdk/Trace/BatchSpanProcessor.php, sdk/Trace/JaegerExporter.php, sdk/Trace/SimpleSpanProcessor.php, sdk/Trace/SpanMultiProcessor.php, sdk/Trace/SpanProcessor.php, sdk/Trace/TracerProvider.php, sdk/Trace/ZipkinExporter.php, tests/unit/Exporter/JaegerExporterTest.php, tests/unit/Exporter/ZipkinExporterTest.php, tests/unit/Trace/SpanProcessor/BatchSpanProcessorTest.php, tests/unit/Trace/SpanProcessor/SimpleSpanProcessorTest.php, tests/unit/Trace/TracingTest.php
The diff isn't crazy big here, but unfortunately there are several logical changes combined. None of the individual moving parts would make sense without the bigger picture of what they enabled, so it may actually be hard to review in chunks without seeing the end state but I'm happy to break the PR up into logical chunks if desired.
This change also:
- Implements `shutdown()` for `SimpleSpanProcessor` and `BatchSpanProcessor`
- Implements `shutdown()` for the Jaeger and Zipkin Exporter implementations
- Makes Exporters optional for `SpanProcessors` (per spec)
- Changes the `BatchSpanProcessor` such that if *either* the configured batch size OR
the configured delay is reached, then a batch is sent, both are no longer required
- Adds `SpanProcessor::forceFlush()` (per spec)
I didn't see …
=> Implement SpanProcessor::shutdown()

tests/Contrib/Unit/ZipkinSpanConverterTest.php
After https://github.com/open-telemetry/opentelemetry-php/pull/97 was merged, some styling gone wrong.
=> fix ZipkinSpanConverterTest style

contrib/Zipkin/Exporter.php
- This change prevents output from being sent to the client during the request.
=> Fix - Remove debug code from Zipkin exporter

.phan/config.php, composer.json, contrib/Zipkin/Exporter.php, tests/Contrib/Unit/ZipkinExporterTest.php, tests/Contrib/Unit/ZipkinSpanConverterTest.php
I added the possibility to inject external HTTP client to the exporters, in order to ease the configuration of it. I thought this will be the simplest way, to have a configured HTTP client.
Also, I improved the tests coverage and implement the exporter return based on zipkin/jaeger server response code.
=> external http client on exporters

sdk/Trace/Span.php, tests/Sdk/Unit/Trace/SpanOptionsTest.php, tests/Sdk/Unit/Trace/TracingTest.php
Post discussion in gitter about an issue with creating spans from options (outlined [in this gist](https://gist.github.com/benagricola/4b86214497244b178ba85d97c2d17e34)).
- Refactor implementation of `$span->replaceAttributes()` to copy input to attributes property rather than iterating.
- Add relevant tests for `SpanOptions`.
- Refactor existing tests passing array to `$span->replaceAttributes()`.
Potentially conflicts with #146 as both add `SpanOptionsTest.php`
=> replaceAttributes should only accept Attributes()

sdk/Trace/Sampler/AlwaysOnSampler.php, sdk/Trace/Sampler/AlwaysParentSampler.php, sdk/Trace/Sampler/ProbabilitySampler.php, sdk/Trace/SamplingResult.php, tests/Sdk/Unit/Trace/SpanResultTest.php
Closes #139 
- Attributes and Links are passed to `SamplingResult` constructor
- Added getter for Links.
- Added test for getters
- Examples are fixed accordingly
=> Added SamplingResult getters for attributes and links

README.md
I realized we never updated the build badge to reflect Github Actions rather than Travis CI.  This PR does just that.
=> Updating Github Actions Badge

.phan/config.php, Context/Context.php, api/CorrelationContext.php, phpunit.xml.dist, sdk/CorrelationContext.php, tests/Context/Unit/ContextTest.php, tests/Sdk/Unit/CorrelationContext/CorrelationContextTest.php
Add `Context` and `CorrelationContext` via standard inheritance.
When subclassing `Context` it is necessary to shadow the `$parent` attr to ensure that all operations on a `CorrelationContext` also return a `CorrelationContext` instead of a `Context`
=> Context and correlationcontext inheritance

api/Trace/Span.php, api/Trace/SpanOptions.php, contrib/Zipkin/SpanConverter.php, sdk/Trace/Span.php, sdk/Trace/SpanOptions.php, sdk/Trace/Tracer.php, tests/Contrib/Unit/ZipkinSpanConverterTest.php, tests/Sdk/Unit/Trace/SpanOptionsTest.php, tests/Sdk/Unit/Trace/TracingTest.php
As reported here https://zipkin.io/zipkin-api/#/default/post_spans: 'Epoch microseconds of the start of this span, possibly absent if incomplete.'
=> timestamp should be span start timestamp

sdk/Trace/SpanContext.php, sdk/Trace/TracerProvider.php, tests/Sdk/Unit/Trace/SpanContextTest.php
Closes #156 
The idea is to change default span context behavior so that the first context is sampled by default
=> Fixes for trace examples

api/Metrics/UpDownCounter.php, sdk/Metrics/UpDownCounter.php, tests/Sdk/Unit/Metrics/CounterTest.php, tests/Sdk/Unit/Metrics/UpDownCounterTest.php
* Initial UpDownCounter commit.
* Unit tests included.
`UpDownCounter` extends `AbstractMetric` from the `Metrics api` [pull request](https://github.com/open-telemetry/opentelemetry-php/pull/155/files).
=> Implement an UpDownCounter Instrument for the Metrics API

api/Metrics/ValueRecorder.php, sdk/Metrics/ValueRecorder.php, tests/Sdk/Unit/Metrics/ValueRecorderTest.php
* Unit tests included.
* Initial ValueRecorder commit.
`ValueRecorder` depends on and extends `AbstractMetric` from the `Metrics api` [pull request](https://github.com/open-telemetry/opentelemetry-php/pull/155/files).
=> Implement a ValueRecorder Instrument for the Metrics API

api/Metrics/Meter.php, sdk/Metrics/Meter.php, sdk/Metrics/Providers/MeterProvider.php, tests/Sdk/Unit/Metrics/MeterTest.php, tests/Sdk/Unit/Metrics/Providers/GlobalMeterProvicerTest.php
This PR adds a [`Meter Interface`](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#meter-interface) that creates the `Counter`,` UpDownCounter`, and `ValueRecoder` [metric instruments](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#the-instruments) (the other metrics instruments will be added once their implementation is complete).
#113
=> Meter interface

api/Trace/Span.php
See https://github.com/open-telemetry/opentelemetry-specification/pull/840.
=> Remove obsolete TODO for addLazyEvent

README.md
Updating the README.md to include the current project status and a link to the specification matrix.  I have another [PR](https://github.com/open-telemetry/opentelemetry-specification/pull/876) open for the specification matrix update.
=> Update Project Status and Specification Matrix Link

sdk/Trace/Sampler.php, sdk/Trace/Sampler/TraceIdRatioBasedSampler.php, tests/Sdk/Integration/TraceIdRatioBasedSamplerTest.php
fixes #174
references https://github.com/open-telemetry/opentelemetry-specification/pull/611
=> change instances of probabilitysampler to traceidratiobasedsampler

api/Trace/TextMapFormatPropagator.php
fixes #174
References https://github.com/open-telemetry/opentelemetry-specification/pull/793
=> rename instances of  httptext to textmap

sdk/Trace/Sampler/TraceIdRatioBasedSampler.php
When running tests directly on my host via `vendor/bin/phpunit` with `hr_HR.UTF-8` locale, it fails since [`sprintf('%f')` is locale-sensitive](https://www.php.net/manual/en/function.sprintf.php). This uses the non-sensitive `%F`.
=> fix: sprintf() is locale-sensitive

README.md
Mention Jaegar example file in readme
fixes #187
=> Rename example file for zipkin as appropriate

tests/Sdk/Unit/Trace/SpanOptionsTest.php
Fix for incorrectly c+p'd comment in `SpanOptions` tests as discussed in gitter.
=> fix: confusing comment in spanoptions test

api/Trace/Span.php, api/Trace/SpanStatus.php, contrib/Zipkin/SpanConverter.php, sdk/Trace/Span.php, sdk/Trace/SpanContext.php, sdk/Trace/SpanStatus.php, tests/Contrib/Unit/ZipkinSpanConverterTest.php, tests/Sdk/Unit/Support/HasTraceProvider.php, tests/Sdk/Unit/Trace/SpanContextTest.php, tests/Sdk/Unit/Trace/SpanOptionsTest.php, tests/Sdk/Unit/Trace/SpanProcessor/BatchSpanProcessorTest.php, tests/Sdk/Unit/Trace/SpanStatusTest.php
I implemented SpanStatus exporting in ZipkinExporter and fixed some deprecation in unit tests.
Because the StatusCode needs to be exported as Code Name I had to change SpanStatus API and some other implementation in the SDK and convert the code int to string. Here are the specs [Status](https://github.com/open-telemetry/opentelemetry-specification/blob/e0bd41739a92304c0be5d68840f434e281b5f8b2/specification/trace/sdk_exporters/zipkin.md#status).
I am aware that this change may impact the memory footprint and I am open to new solutions.
=> Export SpanStatus

examples/AlwaysOffTraceExample.php
The `$span->addEvent()` waits a $timestamp as second argument, but
we are sending `new Attributes([...` as parameter.
Original code:
=> Fix AlwaysOffTraceExample.php Sample

sdk/Trace/Sampler/TraceIdRatioBasedSampler.php, tests/Sdk/Integration/TraceIdRatioBasedSamplerTest.php
This pull request hopes to resolve this issue: open-telemetry#86 which requires implementation of the ShouldSample function in the TraceIdRatioBasedSampler as described in these specs: https://github.com/open-telemetry/opentelemetry-specification/blob/e0bd41739a92304c0be5d68840f434e281b5f8b2/specification/trace/sdk.md#shouldsample.
The exact algorithm for acquiring the samples based on traceId wasn't described in the Spec, so I took an approach similar to the one implemented in the python sdk but adapted it to php.
opentelemetry-python sampling:
https://github.com/open-telemetry/opentelemetry-python/blob/master/opentelemetry-sdk/src/opentelemetry/sdk/trace/sampling.py
=> Added probability sampling based on TraceId

.github/workflows/php.yml, Makefile, composer.json, psalm.xml, sdk/Metrics/HasLabels.php
Fixes #196 
hello @dkarlovi  @bobstrecansky this PR adds Psalm
running 
`make psalm` or  `./vendor/bin/psalm`
```
Scanning files...
Analyzing files...
ERROR: LessSpecificImplementedReturnType - sdk/Metrics/HasLabels.php:17:34 - The inherited return type 'array<array-key, string>' for OpenTelemetry\Metrics\LabelableMetric::getLabels is more specific than the implemented return type for OpenTelemetry\Sdk\Metrics\HasLabels::getlabels 'array<array-key, mixed>' (see https://psalm.dev/166)
public function getLabels(): array
------------------------------
1 errors found
------------------------------
87 other issues found.
You can display them with --show-info=true
------------------------------
Checks took 0.03 seconds and used 5.745MB of memory
```
On the other hand running
`make psalm-info` …
=> Add psalm static analysis tool to codebase

.github/workflows/php.yml, .gitignore, composer.json, examples/AlwaysOffTraceExample.php, examples/AlwaysOnJaegerExample.php, examples/AlwaysOnZipkinExample.php, phpstan.neon.dist, psalm.xml.dist, tests/Context/Unit/ContextTest.php, tests/Contrib/Unit/ZipkinExporterTest.php, tests/Contrib/Unit/ZipkinSpanConverterTest.php, tests/Sdk/Unit/CorrelationContext/CorrelationContextTest.php, tests/Sdk/Unit/Metrics/Exporters/AbstractExporterTest.php, tests/Sdk/Unit/Metrics/UpDownCounterTest.php, tests/Sdk/Unit/Metrics/ValueRecorderTest.php, tests/Sdk/Unit/Resource/ResourceTest.php, tests/Sdk/Unit/Support/HasTraceProvider.php, tests/Sdk/Unit/Trace/SpanOptionsTest.php, tests/Sdk/Unit/Trace/SpanProcessor/BatchSpanProcessorTest.php, tests/Sdk/Unit/Trace/SpanProcessor/SimpleSpanProcessorTest.php, tests/Sdk/Unit/Trace/TracingTest.php
Changes:
- enabled cache for both PHPStan and Psalm
- enabled Github action output for both PHPStan and Psalm, making them produce nice annotations directly in the PR
- fixes for `tests/` and `examples/` to enable further static analysis there too
There's still a little bit of work done, but this should show you the direction. Remember to check only the last commit since I've based this on #205.
=> chore: add static analysis for tests, examples

sdk/Resource/ResourceInfo.php, sdk/Trace/Span.php, sdk/Trace/SpanOptions.php, sdk/Trace/Tracer.php, sdk/Trace/TracerProvider.php, tests/Sdk/Unit/Resource/ResourceTest.php, tests/Sdk/Unit/Trace/TracerProviderTest.php, tests/Sdk/Unit/Trace/TracingTest.php
* Added functionality to associate a traceprovider resource on a tracer and a tracer resource with a span.
* Added a `defaultResource` method to `ResourceInfo`.
* Added test cases to ‘ResourceTest.php`, `TracerProviderTest.php`, `TracingTest.php`.
=> Associating Spans with their TracerProvider

api/Trace/PropagationSetter.php, api/Trace/TextMapFormatPropagator.php, sdk/Trace/PropagationMap.php, sdk/Trace/TraceContext.php, tests/Sdk/Unit/Trace/PropagationMapTest.php, tests/Sdk/Unit/Trace/TraceContextTest.php
This adds the w3c `traceparent` header propagation. Please see [W3C traceparent documentation](https://www.w3.org/TR/trace-context/#traceparent-header ) for more information. `Tracestate` propagation to follow in another PR.
=> Trace context propagation

README.md, docs/versioning.md
Initial Semantic Versioning Rationale document.
=> Semantic Versioning Rationale

sdk/Trace/Sampler/ParentBased.php, tests/Sdk/Integration/ParentBasedTest.php, tests/Sdk/Unit/Trace/TracerProviderTest.php
This updates `PasentBased` sampler according to the current [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/a72807982622260a1a56e106f1f943a5f330894d/specification/trace/sdk.md#parentbased).
`ParentBased` sampler is a composite and it delegates a decision based on the parent `Span` sampled flag.
=> Update ParentBased sampler according to specs

api/Trace/SpanContext.php, api/Trace/TraceState.php, sdk/Trace/NoopSpan.php, sdk/Trace/SpanContext.php, sdk/Trace/TraceContext.php, sdk/Trace/TraceState.php, tests/Sdk/Integration/Context/SpanContextTest.php, tests/Sdk/Unit/Trace/TraceContextTest.php, tests/Sdk/Unit/Trace/TraceStateTest.php
This adds the first part of `Tracestate` header propagation according to the [W3C Trace Context spec](https://www.w3.org/TR/trace-context/#tracestate-header). The following [operations](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#tracestate) on the `Tracestate` header are also included:
- Get value for a given key
- Add a new key/value pair
- Update an existing value for a given key
- Delete a key/value pair
**Note**: This does not yet include a few more pieces of work that will come in a follow-up PR. (These were split out of this PR to make it a bit easier to review):
1. [Further validation of tracestate limits (max 512 characters)](https://www.w3.org/TR/trace-context/#tracestate-limits).
2. [Validate new key/value entries and …
=> Add Trace Context Tracestate header propagation Part 1

.github/workflows/php.yml, composer.json
@keradus opened https://github.com/open-telemetry/opentelemetry-php/pull/242 to update the version of PHP CS Fixer (which includes support for PHP 8.0) - This PR is a clone of his, mostly because the CLA bot wasn't working correctly for him.  Thank you for your contribution @keradus!
=> Updating PHP CS Fixer (PHP 8.0 support released)

.github/workflows/php.yml
Our default branch has been renamed from `master` to `main`.  This PR makes the same update for our Github Actions for CI so it'll run on the main branch by default.
More discussion [here](https://github.com/open-telemetry/community/issues/402#issuecomment-765562382)
=> Changing master to main in CI

sdk/Trace/TraceState.php, tests/Sdk/Unit/Trace/TraceStateTest.php
This adds the second part of `Tracestate` header propagation (Part 1 was added in #233). The following is included:
1. [Further validation of tracestate limits (max 512 characters)](https://www.w3.org/TR/trace-context/#tracestate-limits).
2. [Validate new key/value entries and ensure they are placed at the beginning of the header](https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field).
3. [Ensure vendors overwrite their previous entry upon reentry to their tracing system](https://www.w3.org/TR/trace-context/#combined-header-value).
=> Trace Context Tracestate header propagation Part 2

api/Trace/SpanStatus.php, sdk/Trace/NoopSpan.php, sdk/Trace/Span.php, sdk/Trace/SpanStatus.php, tests/Sdk/Unit/Trace/NoopSpanTest.php, tests/Sdk/Unit/Trace/SpanStatusTest.php, tests/Sdk/Unit/Trace/TracerProviderTest.php, tests/Sdk/Unit/Trace/TracingTest.php
1) Updated SpanStatus to adhere to the latest [specs](https://github.com/open-telemetry/opentelemetry-specification/blob/418016dc4014f0c64acea74881774d34178bf15a/specification/trace/api.md#set-status).
a) Made `UNSET` the statusCode default.
b) Removed significant amount of status codes that were removed from the [spec](https://github.com/open-telemetry/opentelemetry-specification/commit/30eb18a30dff36422de9a2a851010a87e66e4d9d#diff-1c55a70901ca0a001050f25ba8881a9b841777e6d8eaab500faf20230765ff76).
c) Only allowed `ERROR` codes to set descriptions.
The key points in the spec to notice were:
```
The Span interface MUST provide:
•	An API to set the Status. This SHOULD be called SetStatus. This API takes the StatusCode, and an optional Description, either as individual parameters or as an …
```
=> Modified SpanStatus to conform with the feature-freeze specs.

api/Trace/Tracer.php, sdk/Trace/Tracer.php, tests/Sdk/Unit/Trace/TracingTest.php
1. Pass SpanKind through Tracer span creations functions to Span constructor.
2. Add unit test checking SpanKind after creation.
=> Propagate SpanKind to Span constructor

Makefile, README.md, contrib/ZipkinToNewrelic/Exporter.php, contrib/ZipkinToNewrelic/SpanConverter.php, examples/AlwaysOnZipkinToNewrelicExample.php, tests/Contrib/Unit/ZipkinToNewrelicExporterTest.php, tests/Contrib/Unit/ZipkinToNrSpanConverterTest.php
1) Added a basic zipkin to New Relic exporter to the `contrib` directory and also associated tests.
2) Can easily run from `make trace`
3) It requires an environment variable (`NEW_RELIC_INSERT_KEY`) be set to successfully run.
4) If the env var isn't set, it just skips the example.
=> Basic example to send zipkin style data to a New Relic backend.

Context/ContextValueTrait.php, Context/Scope.php, api/Trace/Tracer.php, examples/ParentSpanExample.php, sdk/Trace/NoopSpan.php, sdk/Trace/Span.php, sdk/Trace/SpanContext.php, sdk/Trace/SpanContextKey.php, sdk/Trace/Tracer.php, sdk/Trace/TracerProvider.php, tests/Context/Unit/ContextValueTraitTest.php, tests/Context/Unit/ScopeTest.php, tests/Sdk/Unit/Trace/TracerTest.php
This PR proposes an idea of `trait ContextValueTrait` and `class Scope` to interact with the current `Context`.
Usage example:
```php
class Span {
use ContextValueTrait;
}
$span = $tracer->startSpan();
$scope = Span::setCurrent($span);
try {
$activeSpan = Span::getCurrent(); // returns $span
} finally {
$scope->close();
}
$activeSpan = Span::getCurrent(); // returns NoopSpan
$span->end();
```
This also can be used in implementation of [Baggage API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md).
=> Add ContextValueTrait and Scope to store in Context

CODEOWNERS
Adding @zsistla and @Fahmy-Mohammed as code owners, as they are now approvers! 🍾
=> Adding additional code owners

contrib/Otlp/Exporter.php, contrib/Zipkin/Exporter.php, contrib/ZipkinToNewrelic/Exporter.php
Remove an unused history middleware from the default HTTP client in Exporter which causes a memory leak.
=> Fix memory leak in Exporter

sdk/Trace/SpanProcessor.php, sdk/Trace/SpanProcessor/BatchSpanProcessor.php, sdk/Trace/SpanProcessor/SimpleSpanProcessor.php, sdk/Trace/SpanProcessor/SpanMultiProcessor.php, sdk/Trace/Tracer.php, tests/Sdk/Integration/SpanProcessorTest.php
Pass the parent Context to the SpanProcessor on Span start.
Fixes #278
=> Update SpanProcessor parameters onStart

contrib/Newrelic/Exporter.php, contrib/Newrelic/SpanConverter.php, examples/AlwaysOnNewrelicExample.php, tests/Contrib/Unit/NewrelicExporterTest.php, tests/Contrib/Unit/NewrelicSpanConverterTest.php
1) Added an experimental New Relic exporter, span converter, example, and tests.
2) Can run from `make trace`
3) It requires an environment variable (`NEW_RELIC_INSERT_KEY`) be set to successfully run.
4) If the env var isn't set, it just skips the example.
=> Experimental exporter, span converter, example, and tests.

sdk/Trace/PropagationMap.php, sdk/Trace/TraceContext.php, tests/Sdk/Unit/Trace/PropagationMapTest.php
This fixes issues with exctracting the `traceparent` and `tracestate` headers. This includes:
- Using the correct `traceparent` and `tracestate` header names.
- Account for a case where each header value is represented as an array instead of a string.
=> Fix tracecontext header extraction

examples/AlwaysOffTraceExample.php, examples/AlwaysOnJaegerExample.php, examples/AlwaysOnNewrelicExample.php, examples/AlwaysOnOTLPExample.php, examples/AlwaysOnZipkinExample.php, examples/AlwaysOnZipkinToNewrelicExample.php, sdk/Trace/NoopSpan.php, sdk/Trace/Sampler.php, sdk/Trace/Sampler/AlwaysOffSampler.php, sdk/Trace/Sampler/AlwaysOnSampler.php, sdk/Trace/Sampler/ParentBased.php, sdk/Trace/Sampler/TraceIdRatioBasedSampler.php, sdk/Trace/SamplingResult.php, sdk/Trace/Tracer.php, sdk/Trace/TracerProvider.php, tests/Sdk/Integration/AlwaysOffSamplerTest.php, tests/Sdk/Integration/AlwaysOnSamplerTest.php, tests/Sdk/Integration/ParentBasedTest.php, tests/Sdk/Integration/TraceIdRatioBasedSamplerTest.php, tests/Sdk/Integration/TracerTest.php, tests/Sdk/Unit/Trace/SamplingResultTest.php, tests/Sdk/Unit/Trace/TracerProviderTest.php
* Change shouldSample() method signature to accept the Context
* Default sampler is ParentBased(root=AlwaysOn)
* Avoid to start sampled and non-recording span, return NooSpan
* Change names of SamplingResult constants: DROP, RECORD_ONLY, RECORD_AND_SAMPLE
* Return an updated TraceState in SamplingResult (parent TraceState by default)
* Merge Attributes from the SamplingResult with the Attributes provided in the startSpan method
Fixes #268
=> Update sampling behavior

Makefile, docker-compose-collector.yaml, docker-compose.yaml, docker/Dockerfile, files/collector/otel-collector-config.yml
* Added grpc capabilities to the PHP container dockerfile.
* Added an otel collector (exports to `logging`) to `docker-compose.yaml` to exercise the OTLPGrpc Exporter.
* Edited Makefile to call the OTLPGrpc example.
* Added a file needed to configure the otel collector to send traces directly to logging.
This will automatically spin up an `otel/opentelemetry-collector-contrib` otel [collector](https://github.com/open-telemetry/opentelemetry-collector-contrib) and functional backends to easily demonstrate the newest functionality of the OTLP Grpc Exporter once #272  is merged. This streamlines the process by adding it to the examples in the Makefile.  If users want to experiment with their own credentials/otel backends, they just need to modify `files/collector/otel-collector-config.yml` …
=> Updated components of automated examples.

.gitignore, Makefile, docker-compose.w3cTraceContext.yaml, phpstan.neon.dist, psalm.xml.dist, tests/TraceContext/W3CTestService/README.md, tests/TraceContext/W3CTestService/TestController.php, tests/TraceContext/W3CTestService/index.php, tests/TraceContext/W3CTestService/symfony-setup
This fixes #217.
There are currently 11 tests (out of 40) that are failing. These are mostly related to the `tracestate` header and will be fixed as part of #181. See the `README` for info on how to run the test.
=> W3c trace context test service

README.md, codecov.yml
This PR accomplishes two things:
* Fixes a couple typos and formatting issues in the `README.md`.
* Defines a `codecov.yml`, which makes codecov.io checks not required and updates the patch part of `codecov.io` to not execute.  This was confusing to new maintainers and didn't provide a ton of value.
=> updating codecov.yml and README.md

.github/workflows/psalm-security-analysis.yml
Closes https://github.com/open-telemetry/opentelemetry-php/issues/339.
Adding  the psalm security scan tool for PHP.
=> Adding a github security scan for psalm

docs/laravel-integration.md
opentelemetry-php now ships with ` "guzzlehttp/guzzle": "^7.1.0"`. See: https://github.com/open-telemetry/opentelemetry-php/blob/main/composer.json#L9
This is out of the box compatible with Laravel 8. Therefore this change removes the note about needing to downgrade Guzzle.
=> Remove Note about downgrading Guzzle

sdk/Trace/SpanOptions.php, sdk/Trace/Tracer.php, tests/Sdk/Unit/Trace/TracerTest.php
Resolves span processors being called twice when a `Tracer::startSpan()` span is finished with `Tracer::endActiveSpan()`.
---
Should the `Tracer::endActiveSpan()` method be removed as it is just `::getActiveSpan()->end()` now? The [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.4.0/specification/trace/api.md#tracer-operations) specifies only a create span operation for tracers.
=> Fix span processors being called twice on Tracer::endActiveSpan()

api/Trace/Span.php, sdk/Trace/NoopSpan.php, sdk/Trace/Span.php, tests/Sdk/Unit/Trace/TracingTest.php
[Spec RecordException](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.4.0/specification/trace/api.md#record-exception):
> If RecordException is provided, the method MUST accept an optional parameter to provide any additional event attributes (this SHOULD be done in the same way as for the AddEvent method). If attributes with the same name would be generated by the method already, the additional attributes take precedence.
=> Add attributes parameter to Span::recordException()

docker-compose-collector.yaml, docker-compose.yaml
Changed in jaeger v1.22, https://github.com/jaegertracing/jaeger/blob/master/CHANGELOG.md#1220-2021-02-23
> --collector.zipkin.http-port is replaced by --collector.zipkin.host-port
Resolves https://github.com/open-telemetry/opentelemetry-php/issues/358#issuecomment-861508716.
=> Fix jaeger zipkin-port environment variable

api/Trace/Tracer.php, sdk/Trace/Tracer.php
These two methods are neither used, nor implemented, nor required by spec.
#363
=> Remove not implemented Tracer::finishSpan() and ::deactivateActiveSpan()

contrib/OtlpGrpc/Exporter.php, tests/Contrib/Unit/OTLPGrpcExporterTest.php
Added tests and refactored the code in the OtlpGrpc Exporter to ensure the environment variable for insecure was correctly used. I also fixed another bug I found, which was the incorrect $certificateFile variable was used in the case where `$this->certificateFile !== ''`.
Fixes #368
=> ensure insecure variable is converted to bool

sdk/Trace/RandomIdGenerator.php
This simply makes a random hex generator function from private to public. This was checked to be alright with maintainer @bobstrecansky
=> Change Random Hex generator to public function

sdk/Trace/SpanContext.php, sdk/Trace/TraceContext.php, tests/Sdk/Integration/Context/SpanContextTest.php, tests/Sdk/Unit/Trace/SpanContextTest.php, tests/Sdk/Unit/Trace/TraceContextTest.php
Fixes #371 
This addresses all problems brought up in the above issue.
Updates the `TraceContext` file to conform to specifications. `SpanContext` file was given additional helper functions that are useful for future necessary Id validation.
Tests were updated accordingly. All tests pass.
@Fahmy-Mohammed @bobstrecansky
=> Span context trace context update

sdk/Trace/SpanContext.php, tests/Sdk/Unit/Trace/TracingTest.php
This fixes issue  #378 
This removes all hard coded values and improves the `isValid()` validation.
This should only be a temporary fix to the larger problem described in issue #379
=> SpanContext Issue Temporary Fix

sdk/Trace/SpanOptions.php, sdk/Trace/Tracer.php
This fixes issue #377 
A getter was created to make available the `TracerProvider` from a given Tracer object so that the `IdGenerator` can be reached to generate ids. This getter is similar to the `getResource()` function both in implementation and how it is used in `SpanOptions`.
The changed lines now generate ids according to the provided IdGenerator.
@bobstrecansky @alolita
=> Fixed idgenerator issues in SpanOptions and Tracer

docs/laravel-integration.md, docs/symfony-integration.md, sdk/Trace/Tracer.php, tests/Sdk/Unit/Trace/TracerTest.php
This fixes processing of attributes provided in the SamplingResult. Previously they were either broken (Attribute instance as value) or not present at all.
I also added `null, $sampler` to the TracerProvider args in the examples, so that one is not confused why e.g. attributes are not applied when trying another sampler than the AlwaysOnSampler.
=> Fix merging of attributes provided within SamplingResult in Tracer

Makefile, sdk/Trace/Span.php, tests/Sdk/Unit/Trace/TracingTest.php
Fixes #388 
This adds a better stacktracing function that provides more detail and supports exception chaining.
This simply replaces the `getTraceAsString()` function. 
Removes dry run for make style
=> Stacktrace improvement

docker-compose-collector.yaml
Why? There are no linux/arm64 images for the collector yet: (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2379)
Developing on Apple M1 I found the container would core dump, passing this platform flag forces Docker to run the collector image under Rosetta 2: https://docs.docker.com/docker-for-mac/apple-silicon/#known-issues
I don't forsee any issues for users on Intel Mac, Linux or Windows as each of these platforms would also be required to run the linux/amd64 image.
=> chore: Force otel-collector to use linux/amd64 image in local dev

sdk/InstrumentationLibrary.php, sdk/Trace/Span.php, sdk/Trace/Tracer.php, sdk/Trace/TracerProvider.php, tests/Sdk/Integration/TracerTest.php, tests/Sdk/Unit/Trace/SpanContextTest.php, tests/Sdk/Unit/Trace/SpanProcessor/SimpleSpanProcessorTest.php, tests/Sdk/Unit/Trace/TracerProviderTest.php, tests/Sdk/Unit/Trace/TracingTest.php
Fixes #228.
An `InstrumentationLibrary` is associated with the `Tracer` on every `getTracer()` call and then with its' `Span`s.
This PR adds some "todo" with the `Span::setInstrumentationLibrary()` method. It should be a part of `Span` creation method, but the change of the `Span`'s constructor signature causes huge refactoring and adds a complexity for the code review at the current PR.
=> Reintroduce InstrumentationLibrary

api/Trace/Tracer.php
This PR adds a method defined within the Tracer file called startActiveSpan to the interface that Tracer implements. The reason this is done is so that psalm does not throw an error for using a function not defined within the interface.
Currently the Tracer.php file has many vestigial functions. However, this PR provides a temporary fix for the addition of sample apps to the contrib repository.
=> Fix Tracer Interface

contrib/OtlpGrpc/SpanConverter.php, contrib/OtlpHttp/SpanConverter.php, tests/Contrib/Unit/OTLPGrpcSpanConverterTest.php, tests/Contrib/Unit/OTLPHttpExporterTest.php, tests/Contrib/Unit/OTLPHttpSpanConverterTest.php
Fixes #325
This PR adds `InstrumentationLibrary` information to the OTLP-exported `Span`s.
It also fixes the way how exported `Span`s are combined — by the `InstrumentationLIbrary` produced these `Span`s.
=> Add InstrumentationLibrary in OTLP exporter

api/Trace/Span.php, sdk/Trace/NoopSpan.php, sdk/Trace/Span.php
By allowing recordException accept Throwable, we can record PHP internal errors in OpenTelemetry.
=> Make span.recordException accept Throwable

.gitignore, api/Trace/TraceState.php, contrib/OtlpGrpc/SpanConverter.php, contrib/OtlpHttp/SpanConverter.php, sdk/Trace/Link.php, sdk/Trace/Links.php, sdk/Trace/Span.php, sdk/Trace/TraceContext.php, sdk/Trace/TraceState.php, sdk/Trace/Tracer.php, tests/Contrib/Unit/OTLPGrpcSpanConverterTest.php, tests/Contrib/Unit/OTLPHttpSpanConverterTest.php, tests/Sdk/Unit/Trace/TraceContextTest.php, tests/Sdk/Unit/Trace/TraceStateTest.php, tests/Sdk/Unit/Trace/TracerTest.php, tests/Sdk/Unit/Trace/TracingTest.php
First pass at supporting links.
* Add links to both otlp gprc and proto exporters
* Also includes `trace_state` information as it was needed for links
* Replace `TraceState#build` with `TraceState#__toString`
* This felt like a more idiomatic implementation because `null` gets casted to an empty string so you can just do `(string) $context->getTraceState()` versus needing to make sure it's not `null` before calling `build`. Similarly both `null` and `''` are falsely so conditional logic would treat them both the same.
* Update `TraceContext` to not include the `tracestate` header of the value would be empty
* The spec says empty headers should avoid being sent
Some outstanding questions
* Should there be a `links` argument on the constructor of `Span`?
* Currently the tracer is just …
=> Implement links

sdk/Trace/Events.php, sdk/Trace/Span.php, tests/Contrib/Unit/OTLPHttpSpanConverterTest.php, tests/Sdk/Unit/Trace/SpanTest.php
Took me a while to figure out why my recorded exception wasn't showing up in the backend, but it turns out the event's timestamp wasn't in the duration of the span so it wasn't rendered as such.
This PR updates `renderException` and `Events#addEvent` to use `Clock#timestamp` instead of `time()`.
This probably fixes: https://github.com/open-telemetry/opentelemetry-php/issues/227#issuecomment-795151796.
=> Use Clock to get timestamp for events

composer.json, docker/Dockerfile
Needed to also update the version of the `ast` extension, that's at the latest version as well. Didn't find any additional errors so :+1:.
=> Update Phan to latest version

.github/workflows/publish-otel-php-base-docker-image
Currently, a developer for this project uses a docker base image that includes the gRPC extension.  That takes approximately 15-20 minutes to build, causing developer friction.  This PR creates a github action that builds a new opentelemetry-php base docker image on push.  This will be used as the default standard base Docker image in subsequent PRs.
=> Publish OpenTelemetry PHP Base Docker Image

api/Trace/Clock.php, sdk/Trace/SpanProcessor/BatchSpanProcessor.php, sdk/Trace/Test/TestClock.php, tests/Sdk/Unit/Trace/SpanProcessor/BatchSpanProcessorTest.php
* Allow `BatchSpanProcessor` to use any `API\Clock`
* Previously could only use `SDK\Clock` instances
* Clarify and update batch processor to use `nanoTime` since it is calculating elapsed time
* Update unit test to make use of `TestClock`
* Add default timestamp to `TestClock`
=> `BatchSpanProcessor` clock fixes

.phan/config.php, src/Contrib/OtlpHttp/Exporter.php, tests/Contrib/Unit/OTLPHttpExporterTest.php
* Now appends `/v1/traces` to the endpoint if missing
* Now prepends `https://` if either http or https missing (is this good or should this be `http://`
=> Fixes OtlpHttp Endpoint validation/parsing

.gitignore, Makefile, composer.json, depfile.yaml
This PR adds [Deptrac ](https://github.com/qossmic/deptrac) as a tool to test and lint the dependency direction of (sub) packages.
see: https://github.com/open-telemetry/opentelemetry-php/issues/464
- Adds qossmic/deptrac-shim as a composer dev dependency
- Adds a basic dependency configuration (for now ignoring 3rd party dependencies)
- Adds a make target to execute the deptrac command in the test container ("make deptrac")
Once the issues in https://github.com/open-telemetry/opentelemetry-php/issues/464 are fixed, the deptrac command could become part of the CI pipeline (or even before, since issues can be ignored  in the config)
=> Add Deptrac as a dependency testing/linting tool

.gitignore, Makefile
This PR adds a make target to create the PHPunit HTML code coverage report
See [conversation](https://github.com/open-telemetry/opentelemetry-php/pull/474/files/9d64efe0a7530bdd9b67e4247dd17a497e0e9546#r750225346).
=> Add make target to create HTML code coverage report

website_docs/getting_started.md
Hugo will ignore the current `website_docs/getting_started.md` (i.e., it won't appear on the website) because it doesn't have front matter. This PR adds appropriate front matter and includes some copyedits.
/cc @austinlparker
=> Getting started: add front matter so page will display

composer.json, src/Contrib/Zipkin/SpanConverter.php, tests/Contrib/Unit/ZipkinSpanConverterTest.php
Resolves #295 and maybe addresses part of #283 ?
This just covers these 2 parts of [the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/418016dc4014f0c64acea74881774d34178bf15a/specification/trace/sdk_exporters/zipkin.md#opentelemetry-to-zipkin-transformation)
[Remote Endpoint](https://github.com/open-telemetry/opentelemetry-specification/blob/418016dc4014f0c64acea74881774d34178bf15a/specification/trace/sdk_exporters/zipkin.md#remote-endpoint)
[Event Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/418016dc4014f0c64acea74881774d34178bf15a/specification/trace/sdk_exporters/zipkin.md#events)
I co-opted Go's code heavily for both sets of changes, as well as the comments in and around them for context (some of which didn't line up with …
=> Finish Off Zipkin Spec Updates

src/Contrib/OtlpGrpc/SpanConverter.php, src/Contrib/OtlpHttp/SpanConverter.php, tests/Contrib/Unit/OTLPGrpcSpanConverterTest.php, tests/Contrib/Unit/OTLPHttpSpanConverterTest.php
OTLP span exporters, when combined with BatchProcessor, were duplicating all resources once for each span. Since resources are identical for each span, it seemed safe enough to just pick one value for each key. Added tests (more duplicated code to be cleaned up later!)
=> de-duplicating resources from multiple spans

composer.json
closes: https://github.com/open-telemetry/opentelemetry-php/issues/482
As discussed at the meeting, this PR will remove the hard dependecy on the PHP gRPC extension and move it to be a dev requirement. Additionally a "suggest" section is added to composer.json with information, when the ext-grpc is needed.
The gRPC extension may be a hard dependency of a separate Contrib package in the future, if packages are published individually.
The documentation of this change will be addressed in https://github.com/open-telemetry/opentelemetry-php/issues/481, as this depdendency hasn't been documentated before anyway.
=> Make gRPC PHP extension optional

.env.dist, .gitignore, docker-compose.yaml, docker/Dockerfile
This PR reduces the size of the base php image from 627mb to 129mb, and the containers are now run by non privileged user (cotainers were writing as root on local file-system. Some security focused K8S distributions like OpenShift/OKD don't allow privileged users to run containers). Also the PHP version is now 7.4 (instead of 8.0) to ensure compatibility with minimum supported PHP version.
- Uses Alpine (instead of Debain) as base image with smaller footprint
- Uses docker-php-extension-installer
- Strips debug symboly from grpc and xdebug extensions
- Uses a single RUN command to reduce layer size
- ~~Runs containers as alpines standard user "guest"~~
Changes to fix issues mentioned by @brettmc :
The image creates a system user ("php"), which is used to run the container per default. …
=> Optimize base PHP Dockerfile

CODEOWNERS
As discussed at SIG meeting, adding two new code owners who have recently been approved as maintainers (brettmc, tidal), and removing one code owner who has not been heard from in some time (beniamin)
=> adding new maintainers to CODEOWNERS

Makefile, README.md, examples/SpanResources.php, script/semantic-conventions/semconv.sh, script/semantic-conventions/templates/AttributeValues.php.j2, script/semantic-conventions/templates/Attributes.php.j2, src/SDK/Resource/ResourceConstants.php, src/SDK/Resource/ResourceInfo.php, src/SemConv/ResourceAttributeValues.php, src/SemConv/ResourceAttributes.php, src/SemConv/TraceAttributeValues.php, src/SemConv/TraceAttributes.php, tests/SDK/Unit/Resource/ResourceTest.php
This PR adds semantic conventions for Resource and Trace attributes.
Fixes #376.
As spec [says](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#semantic-conventions), semconv is a candidate for the separated package. So generated classes are in their own namespace `\OpenTelemetry\SemConv`.
There is a script to generate PHP classes from yaml semantic conventions files, (usage `SEMCONV_VERSION=1.8.0 make semconv`).
Deprected class `\OpenTelemetry\SDK\Resource\ResourceConstants`.
=> Add semantic conventions for Resource and Trace attributes

src/Context/Context.php, src/Context/ContextStorageInterface.php, src/SDK/Trace/NoopSpanBuilder.php, src/SDK/Trace/NoopTracer.php, tests/SDK/Unit/Trace/NoopSpanBuilderTest.php
[Specification - Behavior of the API in the absence of an installed SDK](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.8.0/specification/trace/api.md#behavior-of-the-api-in-the-absence-of-an-installed-sdk):
> The API MUST create a non-recording Span with the SpanContext that is in the Span in the parent Context (whether explicitly given or implicit current) or, if the parent is a non-recording Span (which it usually always is if no SDK is present), it MAY return the parent Span back from the creation method.
=> Fix noop SpanContext propagation

.github/workflows/php.yml, Makefile, depfile.yaml, src/Context/ZendObserverFiber.php, src/Contrib/OtlpGrpc/Exporter.php, src/Contrib/OtlpHttp/Exporter.php, src/SDK/Trace/ExporterFactory.php, src/SDK/Trace/SpanExporter/LoggerExporter.php, tests/Contrib/Unit/AbstractHttpExporterTest.php, tests/Contrib/Unit/JaegerExporterTest.php, tests/Contrib/Unit/NewrelicExporterTest.php, tests/Contrib/Unit/OTLPGrpcExporterTest.php, tests/Contrib/Unit/OTLPHttpExporterTest.php, tests/Contrib/Unit/ZipkinExporterTest.php, tests/Contrib/Unit/ZipkinToNewrelicExporterTest.php, tests/SDK/Unit/Trace/ExporterFactoryTest.php
closes: https://github.com/open-telemetry/opentelemetry-php/issues/464
This PR fixes the last issues from https://github.com/open-telemetry/opentelemetry-php/issues/464 
by providing a temporary solution for the dependency of the exporter factory on the contrib package/components.
Since the development for SDK configuration is on hold (for now), a temporary solution to fix said issues was needed.
This PR also activates the deptrac dependency check as required for passing CI.
(deptrac check can be updated to deal with 3rd party dependencies in the future)
(Rework of the exporter-factories and exporters is still WIP and will probably improve or remove this temporary solution)
=> Fix dependency violations in exporter factory

composer.json, src/Contrib/composer.json, src/SDK/Logs/SimplePsrFileLogger.php, src/SDK/composer.json
In PHP >= 8 psr/log versions ^2.0 or ^3.0 are loaded by default (stronger typed than version1).
Allowing these packages to be loaded allows opentelemetry-php to be added without having to downgrade psr/log.
=> Allow psr/log ^2.0 and ^3.0

.php-cs-fixer.php
Following open-telemetry#533, this PR adds a rule for the PHP-CS-Fixer to enforce camel case for the test method names.
=> Enforce snake_case for test method names

.github/workflows/php.yml
Add PHP version flag to codecoverage upload.
This will hopefully help prevent flaky codecoverage reports in the future.
=> Add PHP version flag to codecoverage upload

src/Contrib/Jaeger/SpanConverter.php, tests/Unit/Contrib/JaegerSpanConverterTest.php
The[ Jaeger spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#opentelemetry-to-jaeger-transformation) mentions near the top that the "[generic spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/non-otlp.md#dropped-links-count)" for all exporters also applies, so this implements those requirements (except for the "dropped" ones. I opened an issue in the [spec repo](https://github.com/open-telemetry/opentelemetry-specification/issues/2268) about whether those should be followed)
I drew inspiration from these other language libraries' implementations while putting this together
[Java](https://github.com/open-telemetry/opentelemetry-java/blob/e0854d6ac11cfe4c3794 …
=> Satisfy base spec for Jaeger Thrift span conversion

.phan/config.php, composer.json
As discussesdin https://github.com/open-telemetry/opentelemetry-php/issues/296#issuecomment-987684152 , the original `apache/thrift`composer package includes the code of all language implementations, which makes the package rather huge (~15mb).
The package `packaged/thrift` only includes the thrift PHP code extracted from the original repo as a drop-in replacement. According to [packagist](https://packagist.org/?query=thrift), this package is even more widely used than the original one.
=> Replace apache/thrift with packaged/thrift

src/Contrib/Jaeger/SpanConverter.php, tests/Unit/Contrib/JaegerSpanConverterTest.php
Implements the following sections of the spec
[SpanKind](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#spankind)
[Events](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#events)
Also did some refactoring of the SpanConverter.php file since I was getting confused keeping track of where stuff was at first.
Main thing I was unsure about was how to do an array_map with a static method (ended up wrapping in an anonymous function but that seemed odd)
=> Some incremental progress on Jaeger spec compliance

src/SDK/Trace/RandomIdGenerator.php
psalm has started to complain that random_bytes must receive a positive integer. We always
provide a positive integer, so suppress the warning. In passing, make randomHex method
private, since it is not called from anywhere that I can find.
=> fixing psalm error

src/SDK/Resource/Detectors/Environment.php, tests/Unit/SDK/Resource/ResourceTest.php
PR for #586. Using accessor and environment constant to fetch attributes from the environment variable. However, according to the [environment variable SDK configuration](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#general-sdk-configuration), OTEL_SERVICE_NAME has no default value. This will give an exception because of the way Accessor is implemented. Adding the conditional fetch for value of OTEL_SERVICE_NAME.
=> Refactored Environment.php to use Environment constants and accessor

src/SDK/Trace/SpanProcessorFactory.php, tests/Unit/SDK/Trace/SpanProcessorFactoryTest.php
Refactored SpanProcessorFactory and updated corresponding unit tests. The default value for `OTEL_PHP_TRACES_PROCESSOR` is `batch` so removed null span processor test and replaced it with default span processor test.
Fixes #593.
=> Refactored SpanProcessorFactory to use environment constants and accessor

.github/stale.yml
Adjustments to stale-bot configuration as discussed in SIG meeting and slack.
- Change `staleLabel`from `wontfix` to `stale`
- Add `help wanted` to `exemptLabels`
=> Adjust stale-bot config

src/Contrib/OtlpGrpc/Exporter.php, src/Contrib/OtlpHttp/Exporter.php, src/SDK/Common/Environment/EnvironmentVariablesTrait.php
Fixes #590 
Modified the OTLP gPRC and HTTP trace exporters to allow for configuration options overrides by signal specific options to comply with OpenTelemetry specs.
=> Add support for OTLP signal specific environment overrides [#590]

examples/AirGappedTraceDebugging.php, examples/LoggingOfSpanData.php, examples/ParentSpanExample.php, examples/ResourceDetectors.php, src/SDK/Common/Environment/Defaults.php, src/SDK/Common/Environment/KnownValues.php, src/SDK/Common/Environment/ValueTypes.php, src/SDK/Common/Environment/Variables.php, src/SDK/Resource/ResourceInfo.php, tests/Unit/SDK/Resource/ResourceTest.php
Resource detectors can be configured by an environment variable named `OTEL_PHP_DETECTORS`. By default, all resource detectors will be used to get resource info. The type of variable is List and known values are "all, env, host, os, process, process_runtime, sdk, sdk_provided, none". The order of priority is as follows:
1. If "all" is present, it will return resource info from all detectors and won't iterate the list of values.
2. If "all" is not present, it will iterate the list and add new instances of detectors(could raise multiple instances of the same detector but merge will handle duplicate resource info)
3. For "none", specific code is not written. If the list doesn't have "all" or any of the detectors in the list, it will return the equivalent of an empty resource.
"all" > any of …
=> Added OTEL_PHP_DETECTORS environment variable

tests/Unit/Contrib/AbstractHttpExporterTest.php, tests/Unit/Contrib/OTLPGrpcExporterTest.php, tests/Unit/Contrib/OTLPHttpExporterTest.php
phpstan has just started to fail on a couple of test assertions based on their phpdoc return type, eg:
`Call to method PHPUnit\Framework\Assert::assertNotSame() with mixed and mixed will always evaluate to false`
This doesn't consider that assert<Not>Same will also check for whether two objects are the same instance, so
ignore the error.
=> ignoring some new phpstan failures

src/API/Trace/TracerProviderInterface.php, src/Contrib/Otlp/SpanConverter.php, src/SDK/InstrumentationLibrary.php, src/SDK/Trace/TracerProvider.php, tests/Integration/SDK/TracerTest.php, tests/Unit/Context/ScopeTest.php, tests/Unit/Contrib/AbstractHttpExporterTest.php, tests/Unit/Contrib/OTLPGrpcExporterTest.php, tests/Unit/Contrib/OTLPHttpExporterTest.php, tests/Unit/Contrib/OTLPSpanConverterTest.php, tests/Unit/SDK/Trace/TracerProviderTest.php
This PR addresses #445 by adding `schemaUrl` to the `InstrumentationLibrary` and OTLP Span converter.
`schemaUrl` for the `Resource` is already in code but it needs some rework in exporter for proper handling, which is the subject for dedicated PR.
=> Add support for schemaUrl in TracerProvider and OTLP SpanConverter

src/Contrib/OtlpGrpc/Exporter.php
Fixes resolution of `OTEL_EXPORTER_OTLP_INSECURE` and `OTEL_EXPORTER_OTLP_TRACES_INSECURE` Environment Variables in OtlpGrpc Exporter.
=> Fix OTEL_EXPORTER_OTLP_INSECURE env var resolution

src/SDK/Common/Environment/Parser/RatioParser.php
The Exception Message in the RatioParser was incorrectly stating, that the value must be **between** 0 and 1, while those are the minimum and maximum values.
=> Fix Exception Message in RatioParser

tests/Unit/SDK/Resource/Detectors/ComposerTest.php, tests/Unit/SDK/Resource/Detectors/CompositeTest.php, tests/Unit/SDK/Resource/Detectors/ConstantTest.php, tests/Unit/SDK/Resource/Detectors/EnvironmentTest.php, tests/Unit/SDK/Resource/Detectors/HostTest.php, tests/Unit/SDK/Resource/Detectors/OperatingSystemTest.php, tests/Unit/SDK/Resource/Detectors/ProcessRuntimeTest.php, tests/Unit/SDK/Resource/Detectors/ProcessTest.php, tests/Unit/SDK/Resource/Detectors/SdkProvidedTest.php, tests/Unit/SDK/Resource/Detectors/SdkTest.php, tests/Unit/SDK/Resource/ResourceTest.php
Closes #622.
Added separate unit tests files for Resource Detectors. These tests highly overlap with tests in ResourceTest.php but they were not included in the coverage.
=> Resource Detector Unit Tests

src/Contrib/OtlpGrpc/Exporter.php
A bug when fetching settings from environment was causing the grpc exporter to always use our default
value, rather than the one provided to the exporter's constructor.
Fixes #638
=> honour grpc exporter provided endpoint url

tests/Unit/Contrib/IdConverterTest.php
Adds a specific test based on the spec example, since I tried at least twice at the logic and missed both times until @saktib fixed it all up...
Also fixes up some flakiness I noticed after running the tests a few times, like here https://github.com/open-telemetry/opentelemetry-php/runs/5763933166?check_suite_focus=true
=> Add test based on the Jaeger spec

.phan/config.php
was not removed in #642 along with the rest of the library
=> removing brick/math from phan config

Makefile, tests/Integration/SDK/SpanLimitsBuilderTest.php
Added integration tests to verify compliance with the specification matrix.
Covers:
```
OTEL_SPAN_ATTRIBUTE_VALUE_LENGTH_LIMIT
OTEL_SPAN_EVENT_COUNT_LIMIT
OTEL_SPAN_LINK_COUNT_LIMIT
OTEL_EVENT_ATTRIBUTE_COUNT_LIMIT
OTEL_LINK_ATTRIBUTE_COUNT_LIMIT
```
=> Add compliance tests for environment variables

src/SDK/Resource/ResourceInfoFactory.php, tests/Unit/SDK/Resource/ResourceInfoTest.php
Continue with the #445. This PR to resolve a resulting `schemaUrl` when merging `ResourceInfo`s. Reference to [the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/441bafa8eda1697c3f0b975250e421e25da496b8/specification/resource/sdk.md#merge).
=> Resolve schemaUrl when merging ResourceInfo

examples/CreatingANewTraceInTheSameProcess.php
This PR adds a an example of how to create a new trace in the same process by resetting the scope/context.
=> Add example of how to create a new trace in same process

src/Contrib/Jaeger/JaegerTransport.php, src/Contrib/OtlpGrpc/Exporter.php, src/SDK/Behavior/LogsMessagesTrait.php, src/SDK/Trace/SpanProcessor/SimpleSpanProcessor.php, src/SDK/Trace/TracerProviderFactory.php, tests/Integration/SDK/SpanLimitsBuilderTest.php
allow logging methods in LogsMessagesTrait to be called from within either a static or non-static method.
in passing, adding a missing coversNothing annotation on a complaining integration test
=> static logging methods

phpunit.xml.dist, src/SDK/Common/Dev/Compatibility/Util.php, tests/Unit/SDK/Common/Dev/Compatibility/UtilTest.php
Since it is a notice about a deprecation it should also use E_USER_DEPRECATED as log level.
NOTICE seems to be not the appropriate log level.
In my case it broke the application in dev mode where Notices are considered errors.
=> replace E_USER_NOTICE with E_USER_DEPRECATED

phpunit.xml.dist, src/SDK/Common/Dev/Compatibility/Util.php, tests/Unit/SDK/Common/Dev/Compatibility/UtilTest.php
Reverts open-telemetry/opentelemetry-php#647
We were discussing this PR internally, and think that the original behaviour was correct and intentional - the BC layer is for the protection of code running in production mode, but not development mode.
=> Revert "replace E_USER_NOTICE with E_USER_DEPRECATED"

.github/workflows/php.yml, README.md
this should make the build green for 8.1, finally. We can now consider 8.1 supported,
and so it moves out of experimental - future 8.1 breaks will fail the pipeline.
=> bump protobuf extension to 3.20.0

src/Contrib/Otlp/SpanConverter.php, src/SDK/Common/Instrumentation/KeyGenerator.php, src/SDK/Common/Util/Helpers.php, src/SDK/Trace/TracerProvider.php, tests/Unit/SDK/Common/Instrumentation/KeyGeneratorTest.php
PR for Issue #619.
Factors key generation logic for InstrumentationLibrary instances out to a helper method in a utils class, replacing generation in `TracerProvider` and `SpanConverter` with calls to the new method.
=> Move InstrumentationLibrary key generation logic out of TracerProvider/SpanConverter [#619]

tests/Integration/SDK/SpanBuilderTest.php, tests/Unit/SDK/Trace/TracerProviderTest.php
Some additional tests for the Span Builder SDK that verify:
1) Attributes are merged correctly
2) Setting attributes after calling `startSpan()` should not work
plus some additional tests for setting null and empty string values to attributes.
UPDATE: _I commented out one of the tests that I was not totally sure of. 
(unsure if `setAttribute()` should work with empty string `''` values.)_
=> Add integration tests for tracing compliance

docker-compose.w3cTraceContext.yaml, tests/TraceContext/W3CTestService/symfony-setup, tests/Unit/API/Trace/NonRecordingSpanTest.php
make w3c-trace-context was suffering from some bitrot, so this change gets it building and
running again. The tests themselves still fail due to further code-related bitrot.
=> fixing w3c-tracecontext test startup

tests/Integration/SDK/Context/SpanContextTest.php, tests/Integration/SDK/TracerTest.php, tests/Unit/SDK/Resource/ResourceInfoFactoryTest.php, tests/Unit/SDK/Trace/SpanTest.php, tests/Unit/SDK/Trace/StatusDataTest.php
=> Add phpunit annotations for compliance tests

docker-compose.w3cTraceContext.yaml
To speed up the test setup, the base docker image is put to use in the docker-compose file for `W3C trace-context validation tests` .
A part of Issue #589
=> Add the base docker image to w3c context validation tests

src/Contrib/Prometheus/PrometheusExporter.php
`PrometheusExporter::doExport()` only allows instances of `OpenTelemetry\SDK\Metrics\Counter` class to be exported. This makes it impossible to export counters extending the `Counter` class or just implementing `CounterInterface`.
Allowing any counters implementing `CounterInterface` to be exported would make things easier.
=> Allow custom counters implementing CounterInterface to be exported

src/SDK/Common/Dev/Compatibility/BC/InstrumentationLibraryInterface.php, src/SDK/Common/Dev/Compatibility/_load.php
This should resolve "does not comply with psr-4 autoloading standard" for InstrumentationLibraryInterface
=> fixing psr4 warnings in BC layer

src/Contrib/composer.json
Working on validating the installation of the individual packages atm.
This was the first find.
=> Remove invalid dependency in contrib composer config

examples/AirGappedTraceDebugging.php, examples/BatchExporting.php, examples/ConcurrentSpans.php, examples/ConfigurationFromEnvironment.php, examples/CreatingANewTraceInTheSameProcess.php, examples/DefaultTracer.php, examples/GettingStarted.php, examples/LoggingOfSpanData.php, examples/ParentSpanExample.php, examples/ResourceDetectors.php, examples/SpanResources.php
it's important to detach scope for any activated span (especially in async runtimes), so ensure that the examples show it being done where possible.
In passing, fix some broken examples.
=> adding scope detach to examples

src/SDK/Common/Util/TracingUtil.php, src/SDK/Trace/Span.php, tests/Unit/SDK/Trace/SpanTest.php
=> #632 : Move stack trace formatting out of Span class

src/SDK/Common/Exception/StackTraceFormatter.php, src/SDK/Common/Util/TracingUtil.php, src/SDK/Trace/Span.php, tests/Unit/SDK/Common/Util/test_stacktrace_basic.phpt, tests/Unit/SDK/Common/Util/test_stacktrace_circular.phpt, tests/Unit/SDK/Common/Util/test_stacktrace_n_more.phpt, tests/Unit/SDK/Common/Util/test_stacktrace_namespaced.phpt, tests/Unit/SDK/Trace/SpanTest.php
Resolves some issues with the stacktrace formatter.
- Fix "... n more" to fold only identical frames, currently we might lose information due to folding on first seen frame instead of folding last n identical frames as described by Java ("These lines indicate that the remainder of the stack trace for this exception matches the indicated number of frames from the bottom of the stack trace of the exception that was caused by this exception (the "enclosing" exception).")
- Fix exception class names not being converted to dotted format
- Fix functions being shown as `main`
- Fix out-of-memory on circular exception
Example output to highlight some of the differences:
```
Abc.Def.Test: bar
at Abc.Def.Test.create(Test.php:10)
at Abc.Def.run(example.php:8)
at {main}(example.php:12)
Caused by: …
```
=> Improve StackTraceFormatter

src/SDK/Common/Dev/Compatibility/BC/InstrumentationLibraryInterface.php
Correctly aliasing the renamed InstrumentationLibraryInterface to the new InstrumentationScopeInterface
Fixes #702
=> fixing BC alias for InstrumentationLibrary

src/API/Trace/Propagation/B3MultiPropagator.php, src/API/Trace/Propagation/TraceContextPropagator.php, src/API/Trace/SpanContext.php, src/API/Trace/TraceState.php, tests/TraceContext/W3CTestService/TestController.php, tests/TraceContext/W3CTestService/index.php, tests/TraceContext/W3CTestService/symfony-setup, tests/Unit/API/Trace/Propagation/B3MultiPropagatorTest.php, tests/Unit/API/Trace/Propagation/TraceContextPropagatorTest.php, tests/Unit/API/Trace/TraceStateTest.php
Attempts to fix the W3C test service by updating usage patterns to match the refactorings and functional changes that have been applied since it was last updated. The effort remains a work-in-progress with the tests failing due to a reason I've been unable to diagnose yet.
=> Fix W3C test service

src/SDK/Trace/Sampler/AlwaysOnSampler.php, src/SDK/Trace/Sampler/TraceIdRatioBasedSampler.php
Returned attributes are additional attributes; `AlwaysOffSampler` already returns `null`.
["A set of span Attributes that will also be added to the Span."](https://github.com/open-telemetry/opentelemetry-specification/blob/5fb819c72e34cb21fe1ce5acba1dc93c2216ecb1/specification/trace/sdk.md#shouldsample)
=> Change `Sampler`s to return `null` instead of provided attributes

src/SDK/Trace/TracerProvider.php, tests/Unit/SDK/Trace/TracerProviderTest.php
Fix memory leak caused by keeping strong references to every created `TracerProvider` in callback provided to `register_shutdown_function()`.
=> Prevent leaking `TracerProvider` in `register_shutdown_function()`

script/semantic-conventions/semconv.sh, script/semantic-conventions/templates/AttributeValues.php.j2, script/semantic-conventions/templates/Attributes.php.j2, src/SemConv/ResourceAttributeValues.php, src/SemConv/ResourceAttributes.php, src/SemConv/TraceAttributeValues.php, src/SemConv/TraceAttributes.php, src/SemConv/composer.json
- Updates Semantic Conventions Generator script
- Updates generated Code to version 1.12.0
- Changes generated code from classes to interfaces
=> Update Semantic Conventions to version 1.12.0

deptrac.yaml, src/API/Common/Instrumentation/InstrumentationInterface.php, src/API/Common/Instrumentation/InstrumentationTrait.php, src/API/Metrics/NoopMeter.php, src/API/Metrics/NoopMeterProvider.php, src/API/Trace/NoopTracerProvider.php, src/API/composer.json, src/Context/Propagation/NullPropagator.php, tests/Unit/API/Common/Instrumentation/InstrumentationTraitTest.php, tests/Unit/API/Metrics/NoopMeterTest.php, tests/Unit/Context/Propagation/NullPropagatorTest.php
Adds an InstrumentationInterface and InstrumentationTrait which are meant as a base for (contrib) instrumentations.
(Registering/Activating the Instrumentation with the API has yet to be implemted)
=> Add basic InstrumentationInterface and InstrumentationTrait

DEVELOPMENT.md, Makefile, composer.json, docker/Dockerfile, rector.php, src/API/Baggage/BaggageBuilder.php, src/API/Baggage/Propagation/BaggagePropagator.php, src/API/Trace/Propagation/B3MultiPropagator.php, src/API/Trace/Propagation/TraceContextPropagator.php, src/Context/Context.php, src/Context/Propagation/MultiTextMapPropagator.php, src/Contrib/Jaeger/JaegerTransport.php, src/Contrib/Jaeger/SpanConverter.php, src/Contrib/Jaeger/TagFactory/TagFactory.php, src/SDK/Common/Time/ClockFactory.php, src/SDK/Common/Time/StopWatchFactory.php, src/SDK/Trace/TracerProvider.php
As discussed (long ago) we want to use [Rector](https://github.com/rectorphp/rector) to automatically refactor our code base to be more consistent and automate the upgrade to higher PHP Versions once support for a specific version is dropped.
This PR adds rector as a dependecy and applies rules to upgrade the code base completely to PHP 7.4.
(I will add more rector rules gardually in future PRs, as otherwise this will be a nightmare to review)
- Adds rector as a dev dependency
- Adds rector make targets and inclues them in "make all"
- Applies rector PHP 7.4 rules to the code base
- Adds rector info (and missing deptract info) to DEVELOPMENT.md
- Adds intl extension to dev image for better rector performance
=> Add Rector and PHP 7.4 rules

src/Context/Context.php
Brings methods and properties into expected order + some minor changes
=> Refactor Context

DEVELOPMENT.md
Small note about code coverage in DEVELOPMENT.md to remove some ambiguity.
=> Note about code coverage

examples/traces/demo/docker-compose.yml, examples/traces/demo/src/index.php
=> Fix examples/traces/demo

DEVELOPMENT.md, Makefile
this makes the makefile a little easier to grok: now 'make' or 'make help' will list make targets and a brief description of what they do
=> adding help to makefile

src/Contrib/Jaeger/JaegerTransport.php, src/SDK/Trace/Behavior/HttpSpanExporterTrait.php, src/SDK/Trace/TracerProviderFactory.php
Adding some more logging, to address #298
=> logging more errors

composer.json, src/API/composer.json, src/Context/composer.json, src/Contrib/composer.json, src/SDK/composer.json
This PR adds polyfills for PHP versions 8.0, 8.1, 8.2 in order to use certain language features in our PHP 7.4 code base.
- Adds symfony/polyfill-php80
- Adds symfony/polyfill-php81
- Adds symfony/polyfill-php82
(This should also resolve the Phan error in https://github.com/open-telemetry/opentelemetry-php/pull/767)
=> Add polyfills for PHP 8.0, 8.1, 8.2

examples/traces/features/exporters/in_memory.php, src/SDK/Trace/ExporterFactory.php, src/SDK/Trace/SpanExporter/InMemoryExporter.php, tests/Unit/SDK/Trace/ExporterFactoryTest.php, tests/Unit/SDK/Trace/SpanExporter/InMemoryExporterTest.php
This PR adds an Span InMemoryExporter for testing and debug purposes
- Adds InMemoryExporter 
- Add InMemoryExporter to list of known exporters in ExporterFactory
related: https://github.com/open-telemetry/opentelemetry-php/issues/451
=> Add Span InMemoryExporter

src/SDK/Trace/Tracer.php, tests/Integration/SDK/SpanBuilderTest.php, tests/Integration/SDK/TracerTest.php, tests/Unit/SDK/Trace/TracerTest.php
this completes a todo in code comments: when tracer shared state has shutdown, getting a span builder should return a no-op implementation
=> return no-op span builder after shutdown

src/API/Common/Event/Dispatcher.php, src/API/Common/Event/EmitsEventsTrait.php, tests/Benchmark/EventBench.php, tests/Integration/API/Common/EventContextIntegrationTest.php, tests/Unit/API/Common/Event/DispatcherTest.php, tests/Unit/API/Common/Event/EmitsEventsTraitTest.php
This seems to be the safest way to store the main dispatcher. Using context to store the main event dispatcher causes a scope to be created: activating the newly-created context which stores dispatcher causes a new scope, and that can break things.
I also looked at storing dispatcher in the root context, but that can't work because contexts are immutable.
Closes #778
=> store root dispatcher in a static var

examples/traces/features/always_off_trace_example.php, src/SDK/Trace/Sampler/AlwaysOffSampler.php, src/SDK/Trace/Sampler/AlwaysOnSampler.php, src/SDK/Trace/Sampler/ParentBased.php, src/SDK/Trace/Sampler/TraceIdRatioBasedSampler.php, src/SDK/Trace/SamplerInterface.php, src/SDK/Trace/SpanBuilder.php, src/SDK/Trace/SpanProcessor/BatchSpanProcessor.php, src/SDK/Trace/SpanProcessor/MultiSpanProcessor.php, src/SDK/Trace/SpanProcessor/NoopSpanProcessor.php, src/SDK/Trace/SpanProcessor/SimpleSpanProcessor.php, src/SDK/Trace/SpanProcessorInterface.php, tests/Integration/SDK/AlwaysOffSamplerTest.php, tests/Integration/SDK/AlwaysOnSamplerTest.php, tests/Integration/SDK/ParentBasedTest.php, tests/Integration/SDK/SpanBuilderTest.php, tests/Integration/SDK/TraceIdRatioBasedSamplerTest.php, tests/Unit/SDK/Trace/Sampler/AlwaysOffSamplerTest.php, tests/Unit/SDK/Trace/Sampler/AlwaysOnSamplerTest.php, tests/Unit/SDK/Trace/Sampler/ParentBasedTest.php, tests/Unit/SDK/Trace/Sampler/TraceIdRatioBasedSamplerTest.php, tests/Unit/SDK/Trace/SpanProcessor/BatchSpanProcessorTest.php, tests/Unit/SDK/Trace/SpanProcessor/MultiSpanProcessorTest.php
Prevents having to handle `null` values for parameters that will never be null. Might simplifiy user implementations and removes ambiguity if the meaning of `null` is not obvious.
=> Remove `null` default value from parameters that are never `null`

src/SDK/Common/Future/CancellationInterface.php, src/SDK/Trace/Behavior/SpanExporterDecoratorTrait.php, src/SDK/Trace/Behavior/SpanExporterTrait.php, src/SDK/Trace/SpanExporterInterface.php, src/SDK/Trace/SpanProcessor/BatchSpanProcessor.php, src/SDK/Trace/SpanProcessor/MultiSpanProcessor.php, src/SDK/Trace/SpanProcessor/NoopSpanProcessor.php, src/SDK/Trace/SpanProcessor/SimpleSpanProcessor.php, src/SDK/Trace/SpanProcessorInterface.php, src/SDK/Trace/TracerProvider.php, src/SDK/Trace/TracerProviderInterface.php, src/SDK/Trace/TracerSharedState.php
Allows async implementations to subscribe to timeouts etc.
=> Add basic cancellation support for async implementations

src/SDK/composer.json
`Fatal error: Uncaught Error: Failed opening required 'vendor/composer/../open-telemetry/sdk/src/SDK/Common/Util/functions.php'`
=> Fix incorrect autoload path

src/SDK/Common/Future/CompletedFuture.php, src/SDK/Common/Future/FutureInterface.php, src/SDK/Trace/Behavior/SpanExporterDecoratorTrait.php, src/SDK/Trace/Behavior/SpanExporterTrait.php, src/SDK/Trace/SpanExporterInterface.php, src/SDK/Trace/SpanProcessor/BatchSpanProcessor.php, src/SDK/Trace/SpanProcessor/SimpleSpanProcessor.php, tests/Unit/Contrib/AbstractHttpExporterTest.php, tests/Unit/Contrib/AgentExporterTest.php, tests/Unit/Contrib/JaegerHttpCollectorExporterTest.php, tests/Unit/Contrib/OTLPGrpcExporterTest.php, tests/Unit/Contrib/OTLPHttpExporterTest.php, tests/Unit/SDK/Trace/SpanExporter/AbstractExporterTest.php, tests/Unit/SDK/Trace/SpanExporter/ConsoleSpanExporterTest.php, tests/Unit/SDK/Trace/SpanExporter/LoggerDecoratorTest.php, tests/Unit/SDK/Trace/SpanExporter/LoggerExporterTest.php, tests/Unit/SDK/Trace/SpanProcessor/BatchSpanProcessorTest.php, tests/Unit/SDK/Trace/SpanProcessor/SimpleSpanProcessorTest.php
Related to #788. 
> The return of [Export()](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#exportbatch) is implementation specific. In what is idiomatic for the language the Exporter must send an ExportResult to the Processor. ExportResult has values of either Success or Failure
=> Add support for concurrent exports

docker/Dockerfile
runkit7 is used by AWS instrumentation over in -contrib
in passing, bump ast to latest stable version
=> adding runkit to developer docker image

src/SDK/Trace/SpanProcessor/BatchSpanProcessor.php, src/SDK/Trace/SpanProcessor/SimpleSpanProcessor.php, src/SDK/Trace/SpanProcessorFactory.php, tests/Benchmark/OtlpBench.php, tests/Unit/SDK/Trace/SpanProcessor/BatchSpanProcessorTest.php, tests/Unit/SDK/Trace/SpanProcessor/SimpleSpanProcessorTest.php, tests/Unit/SDK/Trace/SpanProcessorFactoryTest.php
> [Export()](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#exportbatch) will never be called concurrently for the same exporter instance.
This PR calls `::export()` in a synchronous loop to prevent concurrent calls to `::export()`.
Note that this might block the `Span::end()` call that triggered the export longer. The blocking autoflush behavior of `BatchSpanProcessor::onEnd()` can be disabled, spans will then only be flushed on explicit `::forceFlush()` / `::shutdown()` calls.
> [OnEnd()](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#onendspan) MUST be called synchronously within the [Span.End() API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification …
=> Prevent concurrent `::export()` calls in span processor

CODEOWNERS
Update CODEOWNERS to use the @open-telemetry/php-approvers team rather than individual contributor tags
=> Update CODEOWNERS to use the @open-telemetry/php-approvers

src/SDK/Metrics/MetricObserver/MultiObserver.php
metrics observer callbacks can be removed mid-flight, so ignore the false positive
=> ignore phpstan false positive on metrics multiobserver

README.md, src/Contrib/OtlpGrpc/composer.json, src/Contrib/OtlpHttp/composer.json
Exporters can be individually installed via packagist now, so link to them. Also add the `exporter` tag to some exporters that were missed, so they can be found more easily.
=> document exporters as installable packages

README.md, src/Contrib/OtlpGrpc/composer.json, src/Contrib/OtlpHttp/composer.json
Per feedback from #811 the protobuf php library performs badly in real-world scenarios, and shouldn't be used. Document this, and switch the exporters to requiring instead of suggesting the extension.
=> require protobuf extension for otlp exporters

docs/laravel-quickstart.md, src/API/Trace/AbstractSpan.php, src/API/Trace/NonRecordingSpan.php, src/API/Trace/NoopSpanBuilder.php, src/API/Trace/Propagation/TraceContextPropagator.php, src/API/Trace/Span.php, src/Extension/Propagator/B3/B3MultiPropagator.php, src/Extension/Propagator/B3/B3SinglePropagator.php, src/SDK/Metrics/Exemplar/BucketStorage.php, src/SDK/Metrics/Exemplar/ExemplarFilter/WithSampledTraceExemplarFilter.php, src/SDK/Trace/Span.php, tests/Unit/SDK/Metrics/Exemplar/BucketStorageTest.php, tests/Unit/SDK/Metrics/Exemplar/FilteredReservoirTest.php
Unifies access to static interface methods. Other API interfaces with static methods have a class without the `Interface` suffix that provides an implementation, e.g.:
`Baggage::getCurrent(): BaggageInterface`
`SpanContext::getInvalid(): SpanContextInterface`
I considered creating a `Span` class that does not implement `SpanInterface` but disliked the idea of splitting the PHPDoc documentation in different classes.
=> Rename `AbstractSpan` to `Span` for consistent access to static methods

src/Contrib/Otlp/MetricConverter.php, src/Contrib/Otlp/SpanConverter.php, tests/Unit/Contrib/Otlp/MetricConverterTest.php, tests/Unit/Contrib/Otlp/OTLPSpanConverterTest.php
Send InstrumentationScope attributes and dropped attributes count.
Closes #738
=> export otlp InstrumentationScope attributes

src/Contrib/Jaeger/AgentExporter.php, src/Contrib/Jaeger/HttpCollectorExporter.php, src/Contrib/Newrelic/Exporter.php, src/Contrib/OtlpGrpc/Exporter.php, src/Contrib/OtlpHttp/Exporter.php, src/Contrib/Zipkin/Exporter.php, src/Contrib/ZipkinToNewrelic/Exporter.php, src/SDK/Trace/Behavior/SpanExporterDecoratorTrait.php, src/SDK/Trace/Behavior/SpanExporterTrait.php, src/SDK/Trace/SpanExporter/ConsoleSpanExporter.php, src/SDK/Trace/SpanExporter/InMemoryExporter.php, src/SDK/Trace/SpanExporter/LoggerDecorator.php, src/SDK/Trace/SpanExporter/LoggerExporter.php, src/SDK/Trace/SpanExporterInterface.php, tests/Unit/Contrib/AbstractHttpExporterTest.php, tests/Unit/Contrib/Jaeger/AgentExporterTest.php, tests/Unit/Contrib/Jaeger/JaegerHttpCollectorExporterTest.php, tests/Unit/Contrib/OtlpGrpc/OTLPGrpcExporterTest.php, tests/Unit/Contrib/OtlpHttp/OTLPHttpExporterTest.php, tests/Unit/SDK/Trace/SpanExporter/AbstractExporterTest.php, tests/Unit/SDK/Trace/SpanExporter/ConsoleSpanExporterTest.php, tests/Unit/SDK/Trace/SpanExporter/LoggerDecoratorTest.php, tests/Unit/SDK/Trace/SpanExporter/LoggerExporterTest.php
=> Change `SpanExporter::export()` return value to boolean

src/Context/ZendObserverFiber.php, src/Context/composer.json, src/Context/fiber/initialize_fiber_handler.php, tests/Integration/Context/Fiber/test_context_switching_ffi_observer.phpt, tests/Integration/Context/Fiber/test_context_switching_ffi_observer_registered_on_startup.phpt, tests/Integration/Context/Fiber/test_context_switching_not_supported.phpt
Adds missing autoload entry for `initialize_fiber_handler.php` and adds logging if `OTEL_PHP_FIBERS_ENABLED` is enabled and initialization of fiber support fails.
=> Fix fiber support not loaded in `open-telemetry/context`

.env.dist, Makefile
adding the ability to use compose v2 (via .env), and adding a makefile target to locally build dev image
=> docker compose v2 support

examples/disabling_sdk.php, src/SDK/Common/Environment/Defaults.php, src/SDK/Common/Environment/Variables.php, src/SDK/Metrics/MeterProvider.php, src/SDK/SDK.php, src/SDK/Trace/NoopTracerProvider.php, src/SDK/Trace/TracerProvider.php, src/SDK/Trace/TracerProviderFactory.php, tests/Integration/SDK/MeterProviderTest.php, tests/Integration/SDK/TracerTest.php, tests/Unit/SDK/SdkTest.php, tests/Unit/SDK/Trace/TracerProviderFactoryTest.php
Implementing the recently-added OTEL_SDK_DISABLED variable: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#general-sdk-configuration
=> adding OTEL_SDK_DISABLED support

src/Contrib/OtlpGrpc/Exporter.php, tests/Unit/Contrib/OtlpGrpc/OTLPGrpcExporterTest.php
It will throw an `InvalidArgumentException` with the message `Bad metadata value given` if the value in metadata is not an array.
The doc:
https://grpc.io/docs/what-is-grpc/core-concepts/#metadata:~:text=and%20the%20values%20are%20typically%20strings
The grpc source code:
https://github.com/grpc/grpc/blob/2d4f3c56001cd1e1f85734b2f7c5ce5f2797c38a/src/php/ext/grpc/call.c#L114
https://github.com/grpc/grpc/blob/2d4f3c56001cd1e1f85734b2f7c5ce5f2797c38a/src/php/ext/grpc/call.c#L340-L342
=> Grpc metadata value must be an array

composer.json, src/API/Trace/functions.php, src/API/composer.json, tests/Unit/API/Trace/TraceTest.php
Encapsulates the `try-catch-finally` boilerplate code, especially useful for decorators.
```php
$span = $this->tracer
->spanBuilder('example')
->startSpan();
return trace($span, $decorated->method(...), func_get_args());
```
=> Add `trace` convenience function that encapsulates `try-catch-finally` boilerplate code

deptrac.baseline.yaml, src/API/Trace/NonRecordingSpan.php, src/Contrib/OtlpGrpc/Exporter.php, src/SDK/Resource/Detectors/Process.php
Nevay found that an @internal annotation in NonRecordingSpan was the cause of the violation, so remove it.
Closes #718
=> resolve deptrac baseline

src/Contrib/Otlp/ExporterTrait.php, src/Contrib/OtlpGrpc/Exporter.php, src/Contrib/OtlpHttp/Exporter.php, src/SDK/Common/Environment/EnvironmentVariables.php, src/SDK/Common/Environment/EnvironmentVariablesTrait.php, src/SDK/Resource/Detectors/Environment.php, src/SDK/Resource/ResourceInfoFactory.php, src/SDK/SDK.php, src/SDK/Trace/ExporterFactory.php, src/SDK/Trace/SamplerFactory.php, src/SDK/Trace/SpanLimitsBuilder.php, src/SDK/Trace/SpanProcessorFactory.php, tests/Unit/SDK/Common/Environment/EnvironmentVariablesTest.php
The `EnvironmentVariablesTrait` provided instance accessor methods with only static calls. This refactors those methods to be static, removing several cases of anonymous class instantiation to provide its functionality.
It's still possible to access static methods through `$this->` so this is also non-breaking to consumers.
=> refactor: static access for EnvironmentVariablesTrait methods

src/Context/Context.php
=> Remove internal tag from Context::setStorage

src/SDK/Common/Configuration/Configuration.php, src/SDK/Common/Configuration/KnownValues.php, src/SDK/Common/Configuration/Parser/BooleanParser.php, tests/Unit/SDK/Common/Configuration/ConfigurationTest.php, tests/Unit/SDK/Common/Configuration/Parser/BooleanParserTest.php, tests/Unit/SDK/SdkTest.php
per spec, only 'true' and 'false' are valid boolean values. anything else should be interpreted as false and a warning emitted.
Closes #861
=> disallow non-standard boolean config values

src/SDK/Resource/Detectors/Environment.php, tests/Unit/SDK/Resource/Detectors/EnvironmentTest.php
per spec, resource attributes coming from environment should be decoded in the same way that they would be if coming from a header
Closes #786
=> decode OTEL_RESOURCE_ATTRIBUTES values

src/API/Baggage/Metadata.php, src/API/Baggage/Propagation/Parser.php, tests/Benchmark/BaggageParsingBench.php, tests/Unit/API/Baggage/Propagation/ParserTest.php
=> tests and benchmark for baggage parsing

.gitsplit.yml, src/Contrib/Grpc/README.md, src/Contrib/Grpc/composer.json, src/Contrib/Otlp/composer.json, src/Contrib/Zipkin/composer.json, src/Contrib/composer.json
* match grpc's gitsplit destination repo to match package name: 'transport-grpc'
* set autoload->files for contrib modules which support factory registry
=> update contrib autoloading and gitsplit

src/SDK/Trace/SpanProcessor/BatchSpanProcessor.php, src/SDK/Trace/SpanProcessor/SimpleSpanProcessor.php
Resolves #878.
(Matches the behavior of async implementations that create the export fiber in the constructor, [example](https://github.com/Nevay/opentelemetry-php-async/blob/4e55a7d835af42636330689b4e90e53e55a94346/src/SDK/Trace/SpanProcessor/BatchSpanProcessor.php#L129)).
=> Run exports with the `Context` the `SpanProcessor` was created in

src/SDK/Common/Export/Stream/StreamTransportFactory.php, tests/Unit/SDK/Common/Export/Stream/StreamTransportFactoryTest.php
when creating a stream from an endpoint string, the factory wasn't returning the stream. fix and add tests.
=> fix stream transport factory creation

src/SDK/Resource/Detectors/SdkProvided.php, tests/Integration/SDK/ResourceInfoFactoryTest.php, tests/Unit/SDK/Resource/Detectors/SdkProvidedTest.php, tests/Unit/SDK/Resource/ResourceInfoFactoryTest.php
default service name should contain runtime name if available: java just appends ":java" so I did the same.
ref: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#service
=> fixing default service name

src/SDK/Trace/Span.php, tests/Unit/SDK/Trace/SpanTest.php
implement spec-compliance for span status:
- Ok is final
- Unset should be ignored
- only Error may have a desription
- Error can be updated to Ok
ref: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status
=> span status compliance

src/Contrib/Jaeger/AgentExporter.php, src/Contrib/Jaeger/HttpCollectorExporter.php, src/Contrib/Jaeger/HttpSender.php, src/Contrib/Newrelic/Exporter.php, src/Contrib/Newrelic/SpanConverter.php, src/Contrib/Newrelic/SpanExporterFactory.php, src/Contrib/Zipkin/Exporter.php, src/Contrib/Zipkin/SpanConverter.php, src/Contrib/Zipkin/SpanExporterFactory.php, src/Contrib/ZipkinToNewrelic/Exporter.php, src/Contrib/ZipkinToNewrelic/SpanConverter.php, tests/Unit/Contrib/Jaeger/AgentExporterTest.php, tests/Unit/Contrib/Jaeger/JaegerExporterTest.php, tests/Unit/Contrib/Jaeger/JaegerHttpCollectorExporterTest.php, tests/Unit/Contrib/Jaeger/JaegerHttpSenderTest.php, tests/Unit/Contrib/Jaeger/JaegerSpanConverterTest.php, tests/Unit/Contrib/Newrelic/NewrelicExporterTest.php, tests/Unit/Contrib/Newrelic/NewrelicSpanConverterTest.php, tests/Unit/Contrib/Zipkin/ZipkinExporterTest.php, tests/Unit/Contrib/Zipkin/ZipkinSpanConverterTest.php, tests/Unit/Contrib/ZipkinToNewrelic/ZipkinToNewrelicExporterTest.php, tests/Unit/Contrib/ZipkinToNewrelic/ZipkinToNewrelicSpanConverterTest.php
Currently there is no way to set service name from auto instrumentation context for zipkin and newrelic exporters.
We should read that from `OTEL_SERVICE_NAME` or any other configuration settings IMO.
=> allow setting service name from auto instrumentation context

src/API/Trace/SpanContext.php, src/API/Trace/SpanContextInterface.php, src/Contrib/Otlp/SpanConverter.php, tests/Unit/API/Trace/SpanContextTest.php
per spec, https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#retrieving-the-traceid-and-spanid allow retrieving span and trace id as binary (byte array), using `bin2hex`
Update otlp span converter to use the new methods.
=> implement retrieve span and trace id as binary

src/API/Baggage/BaggageInterface.php, src/API/Trace/TraceState.php, tests/Unit/API/Trace/TraceStateTest.php
remove baggage TODOs which have since been done.
implement TODOs from tracestate to log warnings.
tidy up tracestate code, simplify some const names.
=> tracestate + baggage todos

.github/workflows/php.yml, .github/workflows/publish-otel-php-base-docker-image.yml, composer.json, docker-compose.yaml
setting to experimental, as php_cs_fixer is still not ready for 8.2. It can be forced with an env var, but I'll avoid that for now.
bumping a couple of actions versions which have started complaining.
=> adding php8.2 to build matrix

examples/traces/troubleshooting/setting_up_logging.php, src/API/Behavior/LogsMessagesTrait.php, src/API/Common/Log/LoggerHolder.php, tests/Unit/API/Behavior/LogsMessagesTraitTest.php, tests/Unit/API/Trace/Propagation/TraceContextPropagatorTest.php, tests/Unit/API/Trace/TraceStateTest.php, tests/Unit/SDK/Metrics/MeterProviderFactoryTest.php, tests/Unit/SDK/Propagation/PropagatorFactoryTest.php, tests/Unit/SDK/SdkAutoloaderTest.php, tests/Unit/SDK/Trace/SpanExporter/AbstractExporterTest.php, tests/Unit/SDK/Trace/SpanProcessor/BatchSpanProcessorTest.php, tests/Unit/SDK/Trace/SpanProcessor/SimpleSpanProcessorTest.php
Rather than not logging by default, log to console via trigger_error (>= warning), and allow the LoggerHolder mechanism to be used for greater control over logging (including disabling, eg with a NullLogger)
Closes #897
=> default logging to console

src/SDK/Metrics/MetricReader/ExportingReader.php, tests/Unit/SDK/Metrics/MeterProviderTest.php, tests/Unit/SDK/Metrics/MetricReader/ExportingReaderTest.php
If no metrics have been generated, do not send an empty export request (except via forceFlush())
Closes #905
=> do not export empty metrics

examples/traces/demo/docker-compose.yml
Since #838 a endpoint scheme is needed as stated in this [test](https://github.com/open-telemetry/opentelemetry-php/blob/0b43fac/tests/Unit/Contrib/Grpc/GrpcTransportFactoryTest.php#L19).
=> Add scheme to collector endpoint on traces example

src/SDK/Common/Dev/Compatibility/BC/AbstractClock.php, src/SDK/Common/Dev/Compatibility/BC/ClockInterface.php, src/SDK/Common/Dev/Compatibility/BC/InstrumentationLibrary.php, src/SDK/Common/Dev/Compatibility/BC/InstrumentationLibraryInterface.php, src/SDK/Common/Dev/Compatibility/BC/LoggerHolder.php, src/SDK/Common/Dev/Compatibility/BC/OtlpExporter.php, src/SDK/Common/Dev/Compatibility/BC/SystemClock.php
This PR fix `PHP Warning:  Can't preload already declared class ...` errors if PHP preloading is enabled.
=> fix PHP 7.4 preloading errors

.phan/config.php, composer.json, tests/Unit/API/Behavior/LogsMessagesTraitTest.php, tests/Unit/Context/DebugScopeTest.php, tests/Unit/SDK/Common/Dev/Compatibility/UtilTest.php, tests/Unit/SDK/FactoryRegistryTest.php, tests/Unit/SDK/Metrics/Stream/MetricStreamTest.php
phpunit v9.6 introduces a bunch of deprecations for things that will break in v10. This fixes the tests that are currently complaining.
Since PHPUnit v10 requires php 8.1+, it will be some time before we can upgrade
Closes #921
=> fixing phpunit 9.6 deprecations

src/Contrib/Otlp/MetricExporterFactory.php, tests/Unit/Contrib/Otlp/MetricExporterFactoryTest.php
Fixing grpc path and allowing compression from MetricExporterFactory.
Adding tests for MetricExporterFactory.
Replaces #903
=> fixes and tests for MetricExporterFactory

composer.json, script/create_releases.php, script/releases.php
A script to identify which of our git-split repos have changes which are not in a release. It prints out
information about the last release version/date, and provides a link to create a new release via the
github UI.
Lastly, it generates release notes by linking commits back to the PR from upstream.
=> script to identify required releases

composer.json
Don't require grpc package if is not used
=> Move grpc/grpc to dev dependency

src/SDK/Common/Configuration/KnownValues.php, src/SDK/Resource/Detectors/Container.php, src/SDK/Resource/ResourceInfoFactory.php, tests/Unit/SDK/Resource/Detectors/ContainerTest.php
Detect container id from cgroup or mountinfo, based on how otel-js does it.
Closes #931
=> adding container detector

.gitsplit.yml
sdk-contrib is abandoned in packagist, because we publish the packages individually and at independent versions. for the same reason, do not gitsplit tags, only main as we do the tagging in the read-only repos now
=> do not gitsplit sdk-contrib or tags

src/SDK/Common/Configuration/Parser/MapParser.php, tests/Unit/SDK/Common/Configuration/Parser/MapParserTest.php
This change instructs explode to extract at most 2 parts.
Given an example value of 
```
OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic bla64=
```
The config parser would have created three elements, where only two are required. The trailing `=` in base64 headers would then have been effectively discarded, leading to invalid configuration.
=> Ensure base64 encoded values can be used as headers from env

proto/otel/README.md, proto/otel/composer.json, src/Contrib/Otlp/README.md
The runtime library will always be installed, certain discussions on the matter in the Protobuf repo and on the CNFC slack led to the idea of making the runtime library optional. From what I understand, the C extension provides the same FQNCs as the runtime implementation. This way, developers can choose more easily to what to bundle with their projects. 
Documentation about installing either the runtime implementation or C extension have been added to the 2 README files for now. Currently there aren't any other checks to check if either of the 2 is installed. Questions:
1. Do we want this?
2. Where and how do we want to implement this? 
- A `_register.php` like file that checks if either of them (or both) are installed
- Feature detection in the `src/Contrib/Otlp` code where this is …
=> Make protobuf implementation optional

src/Contrib/Otlp/LogsExporter.php, src/Contrib/Otlp/MetricExporter.php, src/Contrib/Otlp/README.md, src/Contrib/Otlp/SpanExporter.php
the otlp exporter will fail to export if there is no protobuf implementation (which we have just made optional, to allow users to choose between extension and native). Add a check to the constructor which will throw a runtime exception. If creating the exporter directly, it will be uncaught. If using a factory, it will report a warning and return a no-op exporter.
Fixes #957
=> fail if no protobuf implementation found

examples/logs/exporters/otlp_http.php, examples/logs/getting_started.php, src/API/Logs/LogRecord.php
clarify that timestamps expect timestamp in nanoseconds, plus minor logging example fixes.
=> adding LogRecord phpdocs

.github/workflows/publish-otel-php-base-docker-image.yml
This adjusts the docker action to build a compatible arm64 image.
I want to use the make scripts with my mac :)
=> Build arm64 base images

.github/workflows/publish-otel-php-base-docker-image.yml
Use correct arm64 platform for building docker images.
My previous PR in #960 used the wrong platform for M1/Apple silicon
=> Use correct platform identifier for Apple Silicon / M1 docker images

Makefile, examples/traces/features/parent_span_example.php, src/Contrib/Newrelic/SpanConverter.php, src/Contrib/Zipkin/SpanConverter.php, tests/Unit/Contrib/Newrelic/NewrelicSpanConverterTest.php, tests/Unit/Contrib/Zipkin/ZipkinSpanConverterTest.php
per spec, exporters MUST report on dropped attributes/links/events using keys defined in spec
Fixes #427
=> report dropped counts in non-otel exporters

src/SDK/Metrics/Data/Exemplar.php, src/SDK/Metrics/Exemplar/BucketStorage.php, src/SDK/Metrics/Exemplar/ExemplarReservoirInterface.php, src/SDK/Metrics/Exemplar/FilteredReservoir.php, src/SDK/Metrics/Exemplar/FixedSizeReservoir.php, src/SDK/Metrics/Exemplar/HistogramBucketReservoir.php, src/SDK/Metrics/Exemplar/NoopReservoir.php, src/SDK/Metrics/MetricFactory/StreamFactory.php, src/SDK/Metrics/MetricFactory/StreamMetricSource.php, src/SDK/Metrics/MetricFactory/StreamMetricSourceProvider.php, src/SDK/Metrics/Stream/AsynchronousMetricCollector.php, src/SDK/Metrics/Stream/AsynchronousMetricStream.php, src/SDK/Metrics/Stream/DeltaStorage.php, src/SDK/Metrics/Stream/Metric.php, src/SDK/Metrics/Stream/MetricAggregator.php, src/SDK/Metrics/Stream/MetricCollectorInterface.php, src/SDK/Metrics/Stream/MetricStreamInterface.php, src/SDK/Metrics/Stream/SynchronousMetricCollector.php, src/SDK/Metrics/Stream/SynchronousMetricStream.php, tests/Unit/Contrib/Otlp/MetricConverterTest.php, tests/Unit/SDK/Metrics/Exemplar/BucketStorageTest.php, tests/Unit/SDK/Metrics/Exemplar/FilteredReservoirTest.php, tests/Unit/SDK/Metrics/Exemplar/FixedSizeReservoirTest.php, tests/Unit/SDK/Metrics/Exemplar/HistogramBucketReservoirTest.php, tests/Unit/SDK/Metrics/Exemplar/NoopReservoirTest.php, tests/Unit/SDK/Metrics/InstrumentTest.php, tests/Unit/SDK/Metrics/Stream/DeltaStorageTest.php, tests/Unit/SDK/Metrics/Stream/MetricStreamTest.php
Preparation for multi-instrument callbacks, moves callback invocations out of asynchronous metric streams.
=> Split metric collection from metric streams

examples/logs/features/monolog-otel-integration.php, src/API/Common/Instrumentation/CachedInstrumentation.php, src/API/Logs/EventLogger.php, src/API/Logs/LoggerInterface.php, src/API/Logs/LoggerProviderInterface.php, src/API/Logs/NoopLogger.php, src/API/Logs/NoopLoggerProvider.php, src/SDK/Logs/Logger.php, src/SDK/Logs/LoggerProvider.php, src/SDK/Logs/NoopLoggerProvider.php, src/SDK/Logs/ReadableLogRecord.php, tests/Unit/API/Logs/EventLoggerTest.php, tests/Unit/SDK/Logs/Exporter/ConsoleExporterTest.php, tests/Unit/SDK/Logs/LoggerTest.php, tests/Unit/SDK/Logs/ReadableLogRecordTest.php
Removing include_trace_context parameter
Set ObservedTimestamp on emit if not already set
Rename logRecord to emit
=> apply logging spec updates

src/API/Behavior/LogsMessagesTrait.php
without a psr-3 logger, we use trigger_error. Using this with E_USER_ERROR is fatal, which is not what we want.
Fixes #968
=> relax default logging levels

README.md
=> fixing symfony link in readme

src/SDK/Metrics/MeterProviderBuilder.php
Currently metric streams are dropped immediately when the last writer goes out of scope.
`ImmediateStalenessHandlerFactory` is mainly useful for tests and doesn't work well with auto instrumentation where instruments are often function scoped.
Resolves #984.
=> Use noop staleness handler factory by default

src/Contrib/Otlp/MetricExporterFactory.php, src/SDK/Common/Configuration/Defaults.php, src/SDK/Common/Configuration/KnownValues.php, src/SDK/Common/Configuration/ValueTypes.php, src/SDK/Common/Configuration/Variables.php, src/SDK/Metrics/MeterProviderFactory.php, tests/Unit/Contrib/Otlp/MetricExporterFactoryTest.php
Implement OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE, which controls the temporality of meters when creating from environment vars. Add OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION to variables, although we do not yet have anything that uses it.
=> temporality preference from env

examples/metrics/exporters/console_from_factory.php, examples/metrics/exporters/otlp_grpc.php, examples/metrics/exporters/otlp_http.php, examples/metrics/exporters/stream.php, src/Contrib/Otlp/ConsoleMetricExporterFactory.php, src/Contrib/Otlp/_register.php, tests/Unit/Contrib/Otlp/ConsoleMetricExporterFactoryTest.php
allow the existing metric exporter to be created from env vars, by creating a factory and registering it against 'console'. Now, `OTEL_METRICS_EXPORTER=console` will create a metrics provider with console output. Note that it lives in contrib/otlp, since it uses the existing otlp converters.
=> adding console metric exporter

src/Context/Context.php, src/Context/ScopeInterface.php
TC review suggests that DETACHED and INACTIVE responses need clarification
Fixes #1018
=> improve documented scope return values

src/API/Trace/NoopSpanBuilder.php, src/API/Trace/SpanBuilderInterface.php, src/SDK/Trace/SpanBuilder.php
TC feedback suggested to rename param to hint at the type (nano seconds)
Fixes #1016
=> rename span builder parameter

examples/metrics/meter_provider_builder.php, src/SDK/Metrics/MeterProviderBuilder.php
adding an example using the meter provider builder, and deprecating a redundant method, `registerMetricReader`
=> adding meter provider builder example

src/API/Trace/SpanInterface.php, src/SDK/Common/Attribute/AttributesBuilder.php, tests/Unit/Contrib/Otlp/SpanConverterTest.php, tests/Unit/Contrib/Zipkin/ZipkinSpanConverterTest.php, tests/Unit/SDK/Common/Attribute/AttributesTest.php, tests/Unit/SDK/Trace/SpanTest.php
* Per spec, arrays MUST contain only the same types. I've allowed for numeric types (integer + double) to be treated as equivalent.
* document span attributes null key/values behaviour
Fixes: #1014
=> drop attributes with non-homogenous array values

src/SDK/Common/Dev/Compatibility/BC/ApiCommon.php, src/SDK/composer.json
- sdk BC was not being loaded at all in the sdk package (only in the monorepo), so add it to autoload->files
- fixing api/common BC layer (removing .php and fixing one of the FQCNs)
=> fixing backwards-compatibility

src/API/Behavior/Internal/Logging.php, src/API/Behavior/LogsMessagesTrait.php, src/API/LoggerHolder.php, tests/Unit/API/Behavior/LogsMessagesTraitTest.php
* adding a backtrace to the errors reported via error_log (which is the default)
* implement OTEL_LOG_LEVEL, which can be used to control which errors are reported via error_log. Note that this doesn't use configuration code from the SDK, as the usage is in the API (because messages are logged from many packages) and deptrac rightly complains about the dependency on SDK.
=> error log backtrace and OTEL_LOG_LEVEL support

src/SDK/Common/Dsn/Dsn.php, src/SDK/Common/Dsn/DsnInterface.php, src/SDK/Common/Dsn/Factory.php, src/SDK/Common/Dsn/FactoryInterface.php, src/SDK/Common/Dsn/Parser.php, src/SDK/Common/Dsn/ParserInterface.php
I can't find any usage of these classes anywhere in main or contrib repo. rather than delete, lets deprecate and remove closer to release candidate
=> deprecate sdk/common/dsn

README.md, proto/otel/README.md, src/API/README.md, src/Context/README.md, src/Contrib/Grpc/README.md, src/Contrib/Otlp/README.md, src/Contrib/Zipkin/README.md, src/Extension/Propagator/B3/README.md, src/SDK/README.md, src/SemConv/README.md
* adding badges to the various readme files to make more obvious the current versions
* list all packages and versions in main readme
* remove old README documentation (excluding development-specific), and direct users to opentelemetry.io
* link to opentelemetry.io where possible in package readme
=> readme badges and cleanup

src/SDK/Common/Attribute/AttributesBuilder.php, tests/Unit/SDK/Trace/SpanTest.php
use reset() instead of trying to get zero array key
=> fixing homogenous check for attributes with non-numeric keys

proto/otel/README.md, proto/otel/composer.json, rector.php, src/Contrib/Otlp/README.md, src/Contrib/Otlp/composer.json
We made protobuf implementation optional back in #949 however it seems to be tripping up a number of developers. Since native + extension can be installed at the same time (with extension taking priority), I think that users will be less surprised when starting out if there is a working implementation by default.
=> require google/protobuf (native)

src/SDK/Common/Attribute/AttributeValidator.php, src/SDK/Common/Attribute/AttributeValidatorInterface.php, src/SDK/Common/Attribute/AttributesBuilder.php, src/SDK/Common/Attribute/AttributesFactory.php, src/SDK/Common/Attribute/AttributesFactoryInterface.php, src/SDK/Common/Attribute/FilteredAttributesFactory.php, src/SDK/Common/Attribute/LogRecordAttributeValidator.php, src/SDK/Logs/ReadableLogRecord.php, tests/Unit/SDK/Common/Attribute/AttributeValidatorTest.php, tests/Unit/SDK/Logs/ReadableLogRecordTest.php
moving private method into a testable class, introduce attribute validation class which applies to most attribute. LogRecord attributes are allowed to be complex, so introduce a validator for these which lets everything through.
Fixes #1074
=> refactor attribute validation

src/Contrib/Otlp/AttributesConverter.php, tests/Unit/API/Behavior/LogsMessagesTraitTest.php, tests/Unit/Contrib/Otlp/AttributesConverterTest.php
if an array is non-simple (has keys), it should be represented as a KeyValue in the generated protobuf-encoded output.
Since we also need to support simple arrays of primitives, I've added a basic check so that those are still represented as ArrayValue.
Fixes #1076
=> handle KeyValue otlp attributes

src/SDK/Metrics/ObservableInstrumentTrait.php
Fixed in PHP 8.1.9 and 8.0.22 (04 Aug 2022), should be fine to remove this now.
=> Remove workaround for php GH-8995

examples/metrics/weak-reference-observables.php, src/API/Metrics/ObservableCallbackInterface.php, src/API/Metrics/ObservableCounterInterface.php, src/API/Metrics/ObservableGaugeInterface.php, src/API/Metrics/ObservableUpDownCounterInterface.php, src/SDK/Logs/Processor/BatchLogRecordProcessor.php, src/SDK/Metrics/ObservableCallback.php, src/SDK/Metrics/ObservableInstrumentTrait.php, src/SDK/Trace/SpanProcessor/BatchSpanProcessor.php, tests/Integration/SDK/MeterProviderTest.php, tests/Unit/SDK/Metrics/InstrumentTest.php
Removes the `$weaken` parameter and always weakens callbacks.
Returned `ObservableCallback`s keep a strong reference to the `$this` of the callback to prevent preemptive gc-ing if the user wants to detach the callback manually.
=> Always weaken asynchronous callbacks

src/Context/README.md, src/Context/ZendObserverFiber.php
They aren't _truly_ safe on NTS builds either, as the functions used are only expected to be set at certain times of the lifecycle, but in practice it's safe enough on NTS.
However, for ZTS, these APIs are not safe to call at runtime at all.
I haven't tested these changes. I simply saw this issue while reading the code and thought I'd offer a starting point by opening a PR instead of just an issue.
=> fix: fiber observers by FFI are not safe on ZTS

src/API/Globals.php, src/API/Instrumentation/ConfigurationResolverInterface.php, src/API/Instrumentation/Configurator.php, src/API/Instrumentation/ContextKeys.php, src/API/Instrumentation/NoopConfigurationResolver.php, src/SDK/Common/Configuration/ConfigurationResolver.php, src/SDK/SdkAutoloader.php, tests/Unit/API/Instrumentation/InstrumentationTest.php, tests/Unit/SDK/SdkAutoloaderTest.php
adding a configuration resolver interface, and api+sdk implementations. the resolver is globally configured. this allows contrib modules to fetch config if an SDK is installed, without directly using the SDK (per spec).
Replaces: #1079
=> adding configuration resolver

examples/metrics/getting_started.php, examples/metrics/weak-reference-observables.php, src/Contrib/Otlp/MetricExporter.php, src/SDK/Metrics/MetricExporter/ConsoleMetricExporter.php, src/SDK/Metrics/MetricExporter/ConsoleMetricExporterFactory.php, src/SDK/Metrics/MetricExporter/InMemoryExporter.php, src/SDK/Metrics/MetricExporter/NoopMetricExporter.php, src/SDK/Metrics/MetricExporterInterface.php, src/SDK/Metrics/MetricReader/ExportingReader.php, src/SDK/Metrics/PushMetricExporterInterface.php, tests/Unit/SDK/Metrics/MetricReader/ExportingReaderTest.php
https://github.com/open-telemetry/opentelemetry-specification/pull/3563 clarifies the behaviour of forceFlush with push/non-push metric exporters.
Break forceFlush out into a PushMetricExporterInterface, and update ExportingReader to only collect/flush if exporter is a push metric exporter.
Fixes #1086
=> adding PushMetricExporterInterface

src/Contrib/Otlp/MetricExporter.php, src/SDK/Metrics/AggregationTemporalitySelectorInterface.php, src/SDK/Metrics/MetricExporter/ConsoleMetricsExporter.php, src/SDK/Metrics/MetricExporter/InMemoryExporter.php, src/SDK/Metrics/MetricExporter/NoopMetricExporter.php, src/SDK/Metrics/MetricExporterInterface.php, src/SDK/Metrics/MetricReader/ExportingReader.php, tests/Unit/Contrib/Otlp/MetricExporterFactoryTest.php, tests/Unit/SDK/Metrics/MetricReader/ExportingReaderTest.php
per TC review, temporality is not part of MetricExporterInterface. Riffing on Java's solution, this moves `temporality` into `AggregationTemporalitySelectorInterface`, and adds that interface to MetricExporter instances that use it (everything except `NoopMetricExporter`).
Closes #1087
=> move temporality into own interface

src/SDK/Resource/Detectors/Environment.php
I've noticed that one of the links in the repo is outdated. Here's a fix
=> chore: fix broken link to env specs

tests/Unit/SDK/FactoryRegistryTest.php, tests/Unit/SDK/Logs/Exporter/InMemoryExporterFactoryTest.php, tests/Unit/SDK/Logs/Exporter/InMemoryExporterTest.php, tests/Unit/SDK/Metrics/MetricExporter/InMemoryExporterFactoryTest.php, tests/Unit/SDK/Metrics/MetricExporter/NoopMetricExporterFactoryTest.php, tests/Unit/SDK/SdkBuilderTest.php, tests/Unit/SDK/Trace/SpanExporter/ConsoleSpanExporterFactoryTest.php, tests/Unit/SDK/Trace/SpanExporter/InMemorySpanExporterFactoryTest.php
As my first code contribution, I wanted to add more test scenarios.
=> improving more tests

src/SemConv/README.md
mention that tags align with the upstream semantic conventions repo
=> update SemConv readme

script/semantic-conventions/semconv.sh, script/semantic-conventions/templates/resource_deprecations.php.partial, src/SDK/Resource/Detectors/Sdk.php, src/SemConv/ResourceAttributes.php, src/SemConv/TraceAttributes.php
Since 1.19.0, the source has been split out of opentelemetry-specifiction into semantic-conventions. Update the build script accordingly. Update to latest generator.
Add 2 new deprecations for semconvs which were renamed since 1.19
=> update semconv to 1.22.0

.gitsplit.yml, composer.json, src/Extension/Propagator/XCloudTrace/README.md, src/Extension/Propagator/XCloudTrace/Utils.php, src/Extension/Propagator/XCloudTrace/XCloudTraceFormatter.php, src/Extension/Propagator/XCloudTrace/XCloudTracePropagator.php, src/Extension/Propagator/XCloudTrace/_register.php, src/Extension/Propagator/XCloudTrace/composer.json, src/SDK/Common/Configuration/KnownValues.php, tests/Unit/Extension/Propagator/XCloudTrace/UtilsTest.php, tests/Unit/Extension/Propagator/XCloudTrace/XCloudTraceFormatterTest.php, tests/Unit/Extension/Propagator/XCloudTrace/XCloudTracePropagatorTest.php, tests/Unit/SDK/FactoryRegistryTest.php, tests/Unit/SDK/Propagation/PropagatorFactoryTest.php
This is an implementation for GCP/Google X-Cloud-Trace-Context header propagator. Propagator for this header is available in most languages except PHP and my team needs it, thus I'm presenting this PR for review.
The formatting/parsing logic is heavily borrowed from OpenCensus implementation with a few changes: https://github.com/census-instrumentation/opencensus-php/blob/master/src/Trace/Propagator/TraceContextFormatter.php
Tests are heavily borrowed from existing B3 Propagator tests in this library.
Please let me know how this needs to be adjusted. This has also been tested end to end with a Slim API and Honeycomb exporter.
=> Implement GCP X-Cloud-Trace-Context Propagator

script/semantic-conventions/semconv.sh, script/semantic-conventions/templates/AttributeValues.php.j2, script/semantic-conventions/templates/Attributes.php.j2, src/SemConv/ResourceAttributes.php, src/SemConv/TraceAttributes.php
a bug in 1.23.0 meant that cloud, container and oci resource attributes were incorrectly published under trace attributes. sort the attributes, so that future diffs are easier to read.
=> generate semconv for 1.23.1

src/API/Metrics/MeterInterface.php, src/API/Metrics/Noop/NoopMeter.php, src/API/composer.json, src/SDK/Metrics/DefaultAggregationProviderInterface.php, src/SDK/Metrics/DefaultAggregationProviderTrait.php, src/SDK/Metrics/Instrument.php, src/SDK/Metrics/Meter.php, src/SDK/Metrics/MetricReader/ExportingReader.php, tests/Unit/SDK/Metrics/MeterTest.php, tests/Unit/SDK/Metrics/MetricReader/ExportingReaderTest.php
See [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.28.0/specification/metrics/api.md#instrument-advisory-parameters), adds an optional `$advisory` parameter to all `Meter::createXXX()` methods.
Use case [`http.server.request.duration`](https://github.com/open-telemetry/semantic-conventions/blob/v1.23.1/docs/http/http-metrics.md#metric-httpserverrequestduration):
> This metric SHOULD be specified with [ExplicitBucketBoundaries](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.26.0/specification/metrics/api.md#instrument-advisory-parameters) of [ 0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1, 2.5, 5, 7.5, 10 ].
=> Add instrument advisory parameter

src/Contrib/Otlp/ProtobufSerializer.php, tests/Unit/Contrib/Otlp/MetricExporterTest.php, tests/Unit/Contrib/Otlp/SpanExporterTest.php
Workaround for #978, traverses the serialized json payload and replaces every enum value with its respective numeric value.
=> Serialize protobuf enums as integer

deptrac.baseline.yaml, deptrac.yaml, src/Extension/Propagator/B3/_register.php, src/Extension/Propagator/CloudTrace/_register.php, src/Extension/Propagator/Jaeger/_register.php
```shell
$ composer init --require open-telemetry/extension-propagator-b3:^1.0 -n && composer u && php vendor/autoload.php
```
```
Fatal error: Uncaught Error: Class "OpenTelemetry\SDK\Registry" not found in /php/propagators-fatal-error/vendor/open-telemetry/extension-propagator-b3/_register.php:9
Stack trace:
#0 /php/propagators-fatal-error/vendor/composer/autoload_real.php(41): require()
#1 /php/propagators-fatal-error/vendor/composer/autoload_real.php(45): {closure}('2cea4639ba6ec5b...', '/php/propagator...')
#2 /php/propagators-fatal-error/vendor/autoload.php(25): ComposerAutoloaderInit35b4c2f542c1313891bfa1d737057525::getLoader()
#3 {main}
thrown in /php/propagators-fatal-error/vendor/open-telemetry/extension-propagator-b3/_register.php on line 9
```
=> Prevent propagator packages from throwing fatal error if sdk not installed

src/SDK/Metrics/Stream/DeltaStorage.php
Only fails if a node that was created after exceeding 63 readers should be merged with a node that was created before exceeding 63 readers, resulting in a `GMP===int` comparison. Affected nodes were still merged on the next `::collect()` call -> solely internal change.
```php
$stream = new SynchronousMetricStream(new SumAggregation(), 0, 2000);
for ($i = 0; $i < 63; $i++) {
$stream->register(Temporality::Delta);
}
$stream->push(new Metric([], [], 0));
$reader = $stream->register(Temporality::Delta);
$stream->push(new Metric([], [], 0));
$stream->collect($reader); // storage should contain a single node at this point
```
=> Fix delta storage failing to merge node under rare circumstances

src/Context/Context.php, src/Context/README.md, tests/Unit/Context/DebugScopeTest.php
Allows disabling debug scopes via `OTEL_PHP_DEBUG_SCOPES_DISABLED`; resolves https://github.com/open-telemetry/opentelemetry-php/pull/1140#issuecomment-1880249248.
=> Add option to disable debug scopes

src/Context/DebugScope.php
Disable warnings for missing calls to `::detach()` during the final shutdown phase if the scope is not destructed in the original fiber; `DebugScope::__destruct()` might be called before the fiber is resumed / before finally blocks that `::detach()` the scope are run.
I wasn't able to create a simple reproducer; it happens for example with `amphp/file ^3.0` and `tbachert/otel-async-revolt-adapter 0.1.1`.
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';
Amp\File\openFile(__FILE__, 'rb');
```
```
... shutdown functions finished
scope 116 ::__destruct() (created in fiber 112, currently in fiber {main})
scope 116 ::detach() (created in fiber 112, currently in fiber 112)
scope 242 ::detach() (created in fiber 148, currently in fiber 148)
scope 242 ::__destruct() (created in fiber …
```
=> Handle out-of-order destruction of Fibers/DebugScopes during final shutdown

src/Contrib/Otlp/OtlpUtil.php, src/Contrib/Otlp/SpanExporterFactory.php, src/SDK/Common/Configuration/Resolver/CompositeResolver.php, src/SDK/Logs/LoggerProviderFactory.php, src/SDK/Metrics/MeterProviderFactory.php, src/SDK/Resource/ResourceInfo.php, src/SDK/SdkAutoloader.php, tests/Benchmark/ResourceCreationBench.php
Profiling the SDK autoloader startup with xdebug, I could see that we re-detect resources multiple times which adds overhead.
- instead of creating new resources from various factories, create them once from sdk autoloader and
pass them to the factories (most of which already supported this).
- cache header from OtlpUtil, to save a couple of constructor calls to Sdk detector
- check env before php.ini for config, since this is the more popular approach and saves some cycles
- note as a todo that we could save some further cycles around resource merging by not re-validating attributes
=> optimize resource creation

src/SDK/Common/Attribute/AttributesBuilder.php, src/SDK/Common/Attribute/AttributesBuilderInterface.php, src/SDK/Common/Attribute/FilteredAttributesBuilder.php, src/SDK/Common/Util/ClassConstantAccessor.php, src/SDK/Resource/ResourceInfo.php, tests/Unit/SDK/Common/Attribute/AttributesTest.php
- do not revalidate/normalize resource attributes on merge, since they have already been validated/normalized
- string concat is about 10x faster than sprintf, so use it in ClassConstantAccessor since it's called many times
=> optimize resource merging

.github/workflows/php.yml
optimize build times by caching php extensions, particularly for 8.4/nightly which otherwise builds extensions from source each time.
Cache key is year+week#, so the first action each week will be particularly slow (~18m for 8.4); the other versions will be slower but tolerable at ~30s
NB that 8.4 now incorrectly reports as passing, but there are some errors visible in the overview.
=> cache php extensions

script/semantic-conventions/semconv.sh, script/semantic-conventions/templates/trace_deprecations.php.partial, src/SemConv/ResourceAttributeValues.php, src/SemConv/ResourceAttributes.php, src/SemConv/TraceAttributeValues.php, src/SemConv/TraceAttributes.php
generate latest semconv version, and add back Trace and Resource attribute values which seem to have been dropped in a previous change.
=> generate semconv 1.24.0

src/API/Behavior/Internal/LogWriter/Formatter.php
it's not always clear from an exception message what the underlying issue was, so also print out the previous exception's message, if available.
Fixes: #1112
=> log previous exception message from error writer

src/Contrib/Otlp/LogsExporterFactory.php, src/Contrib/Otlp/MetricExporterFactory.php, src/Contrib/Otlp/OtlpUtil.php, src/Contrib/Otlp/SpanExporterFactory.php, tests/Unit/Contrib/Otlp/LogsExporterFactoryTest.php, tests/Unit/Contrib/Otlp/MetricExporterFactoryTest.php, tests/Unit/Contrib/Otlp/OtlpUtilTest.php, tests/Unit/Contrib/Otlp/SpanExporterFactoryTest.php
Per a recent spec clarification in https://github.com/open-telemetry/opentelemetry-specification/issues/3832 OTLP headers should support url-encoded header values.
Fixes: #1239
=> support url-encoded OTEL_EXPORTER_OTLP_HEADERS values

src/Context/Context.php, tests/Unit/Context/ContextTest.php
Hi :wave:
While doing some tests and trying to set `OTEL_PHP_DEBUG_SCOPES_DISABLED` to `1` as an **environment variable** to disable the use of `DebugScope`, it wouldn't work. This is because it wasn't considered.
I guess it could have also made sense to use some kind of a `ResolverInterface`, considering both INIs and env var.
Also, my personal opinion on this env var is that it could make sense to have it enabled by default (in the next major, being a breaking change), considering that the use of `debug_backtrace` has a non-negligible performance impact.
=> feat: Allow OTEL_PHP_DEBUG_SCOPES_DISABLED as en environment variable

src/SDK/Resource/ResourceInfoFactory.php
Hello :wave:
While searching for low-hanging fruits to improve performance, it appeared from a profile of mine that repeated calls to `ResourceInfoFactory::emptyResource` would start having a non-negligible impact on the performances.
The instance - being immutable - could be re-used.
Note: I haven't added a test with this PR as imo this is already been tested through the numerous calls to `ResourceInfoFactory::emptyResource`
Thanks! 😃 
---
FYI, this is the code I used to generate the above profile, if you care, which I ran a few dozen thousand times:
```php
function benchOpenTelemetryAPI($tracer) {
$span = $tracer->spanBuilder('bench.basic_scenario')->setParent(false)->startSpan();
$span->setAttribute('foo', 'bar');
$span->setAttribute('bar', 1);
$spans = [];
for ($i = 0; $i < 6; $i++) { …
```
=> perf: Re-use empty resource instance

src/Contrib/Otlp/AttributesConverter.php, tests/Unit/Contrib/Otlp/AttributesConverterTest.php, tests/Unit/Contrib/Otlp/SpanExporterTest.php
[Converting to AnyValue](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-type-mapping.md#string-values):
> String values which are not valid Unicode sequences SHOULD be converted to AnyValue's bytes_value with the bytes representing the string in the original order and format of the source string.
=> Fix conversion of non-utf8 sequences to `AnyValue`

src/SDK/Resource/Detectors/Host.php, tests/Unit/SDK/Resource/Detectors/HostTest.php
Fixes #1263 
Only mocked the file system for Linux.
BSD, MacOS, and Windows all shell out to get the ID. I've added tests covering parsing the output on MacOS and Windows.
Any and all feedback is welcome, I haven't written PHP in a long time.
=> Add host.id for non-containerized systems

.github/workflows/shellcheck.yml, script/proto_gen.sh, script/semantic-conventions/semconv.sh, tests/TraceContext/W3CTestService/trace-context-test.sh
- Use `set -e` rather than repeatedly checking for errors
- Apply suggestion from `shellcheck --severity=warning` to properly quote backtick result
- Add CI step to run `shellcheck --severity=warning`
=> Clean up shell scripts

script/semantic-conventions/semconv.sh, script/semantic-conventions/templates/Attributes.php.j2, src/SemConv/ResourceAttributeValues.php, src/SemConv/ResourceAttributes.php, src/SemConv/TraceAttributeValues.php, src/SemConv/TraceAttributes.php
I'm not sure if there's a workflow for this, but I noticed that there are some missing constants that (I'd like to use and) are already documented at https://opentelemetry.io/docs/specs/semconv/, so I thought I should try to help out... :man_shrugging: 
I only refreshed my local repo and ran `make install`, updated the versions in the script, ran `make semconv` and then `make all` (and all seemed fine) - don't know if that's all or if I should do something else.
=> Update SemConv to 1.25.0

docker-compose.yaml, script/semantic-conventions/README.md, src/SDK/Metrics/Stream/SynchronousMetricStream.php, src/SDK/Resource/Detectors/Host.php, tests/Integration/Config/configurations/kitchen-sink.yaml, tests/Unit/SDK/Resource/Detectors/HostTest.php
A couple of warnings have popped up recently:
- docker compose 'version' is deprecated
- BSD host id test was running a command that doesn't exist, which was visible in test output (removed test case)
- synchronous metric stream test was triggering a warnings which was visible in test output (changed to use LogsMessagesTrait)
- resource merging with different schema URLs was triggering a warnings from Config test (updated yaml schema_url and documented)
=> fixing warnings from local build

src/API/Metrics/GaugeInterface.php, src/API/Metrics/MeterInterface.php, src/API/Metrics/Noop/NoopGauge.php, src/API/Metrics/Noop/NoopMeter.php, src/API/Trace/NonRecordingSpan.php, src/API/Trace/SpanInterface.php, src/API/composer.json, src/SDK/Metrics/DefaultAggregationProviderTrait.php, src/SDK/Metrics/Gauge.php, src/SDK/Metrics/InstrumentType.php, src/SDK/Metrics/Meter.php, src/SDK/Trace/ImmutableSpan.php, src/SDK/Trace/Span.php, src/SDK/composer.json, tests/Integration/SDK/SpanBuilderTest.php, tests/Unit/SDK/Metrics/MeterTest.php, tests/Unit/SDK/Metrics/MetricReader/ExportingReaderTest.php, tests/Unit/SDK/Trace/ImmutableSpanTest.php
Updates traces and metrics API to match spec version 1.32.0.
Not included in this PR are changes to the events API; there were breaking changes to `EventLogger` in v1.28.0, non-breaking changes in v1.31.0.
=> Add `Span::addLink()` and `Meter::createGauge()`

.github/workflows/php.yml
our previous method of uploading to codecov.io is suffering from throttling and taking 5+ hours, a post in the opentelemetry maintainers channel suggests this is the way to do it now
=> use codecov action

src/SDK/Trace/SpanExporter/FriendlySpanConverter.php, tests/Unit/SDK/Trace/SpanExporter/FriendlySpanConverterTest.php
Regarding this issue: https://github.com/open-telemetry/opentelemetry-php/issues/1290
I believe this is the expected way to communicate the scheme used to a collector or downstream system attempting to analyze the telemetry, based on the [documentation](https://opentelemetry.io/docs/specs/otel/schemas/#otlp-support) on the OpenTelemetry website.
Closes: https://github.com/open-telemetry/opentelemetry-php/issues/1290
=> Include schema_url in FriendlySpanConverter

src/API/Baggage/Propagation/BaggagePropagator.php, src/API/Trace/Propagation/TraceContextPropagator.php, src/Context/Propagation/NoopTextMapPropagator.php, src/Context/Propagation/TextMapPropagatorInterface.php, src/SDK/Common/Configuration/Configuration.php
=> [PHP 8.4] Fixes for implicit nullability deprecation

src/SDK/Common/Util/functions.php
PHP8.4 non-first-class-callables include source information in their name -> checking for `{closure}` fails.
> Error: Call to undefined method OpenTelemetry\SDK\Logs\Processor\BatchLogRecordProcessor::{closure:OpenTelemetry\SDK\Logs\Processor\BatchLogRecordProcessor::__construct():100}()
=> Fix `weaken` for PHP8.4 closure names

composer.json
avoid the static analysis issue we have with mockery 1.6.12 by adding a composer conflict
=> conflict with mockery 1.6.12

src/SDK/Logs/ExporterFactory.php
- Use `OTEL_LOGS_EXPORTER` variable in logs exporter factory exception message
=> Fix logs exporter factory exception message

src/SDK/Common/Attribute/AttributesBuilder.php
Using the open-telemetry SDK package in a Symfony project gives us a lot of deprecation messages based on the ArrayAccess methods going to change in the future. This PR tries to solve it in the softest way possible.
I saw that in other places the actual return types were added, but as this code has also `#[\ReturnTypeWillChange]`, I think this code can not be upgraded in the same way yet, right?
=> Add return types for ArrayAccess in docblocks in AttributesBuilder

src/SDK/Common/Export/Http/PsrUtils.php, tests/Unit/SDK/Common/Export/Http/PsrTransportTest.php, tests/Unit/SDK/Common/Export/Http/PsrUtilsTest.php
at least one otel backend product sends an empty response with a gzip encoding, which we fail to decode (because an empty string is not valid). Work around this by not trying to decode an empty value.
Fixes: #1264
=> handle empty encoded responses

.github/workflows/php.yml, src/Extension/Propagator/B3/B3MultiPropagator.php, src/Extension/Propagator/B3/B3Propagator.php, src/Extension/Propagator/B3/B3SinglePropagator.php, src/Extension/Propagator/CloudTrace/CloudTracePropagator.php, src/Extension/Propagator/Jaeger/JaegerBaggagePropagator.php, src/Extension/Propagator/Jaeger/JaegerPropagator.php
implicit nullable parameters are deprecated in 8.4, so make them explicit
bump github action versions to silence deprecation warning
=> fixing implicit nullable deprecations, bump GH actions

script/semantic-conventions/README.md, script/semantic-conventions/semconv.sh, script/semantic-conventions/templates/resource_deprecations.php.partial, script/semantic-conventions/templates/trace_deprecations.php.partial, src/SemConv/ResourceAttributeValues.php, src/SemConv/ResourceAttributes.php, src/SemConv/TraceAttributeValues.php, src/SemConv/TraceAttributes.php, src/SemConv/Version.php, tests/Integration/Config/configurations/kitchen-sink.yaml
note that messaging.client_id was renamed to messaging.client.id, which causes a conflict in const name. It hasn't been resolved upstream yet, but manually removing the duplicate seems like the best way to go for us.
=> update semconv to 1.26.0

.github/workflows/publish-otel-php-base-docker-image.yml
This change adds a base-image for M3 devices using the linux/arm64 arch.
=> Add linux/arm64 to base images support M3 devices

rector.php
this silences a rector warning which was breaking local build
=> remove deprecated rector rule

src/SDK/Common/Attribute/AttributesBuilder.php, src/SDK/Common/Attribute/FilteredAttributesBuilder.php
now that 7.4 and 8.0 support is dropped, we can add correct return type-hints to these functions, and remove the ReturnTypeWillChange attribute.
Fixes: #1348
=> add return type hints to Attributes* classes

src/API/Logs/LateBindingLogger.php, src/API/Trace/LateBindingTracer.php
this was overlooked in a prior PR, and broke the build.
=> add enabled to late binding logger and tracer

composer.json
=> Allow for 'google/protobuf' '^4.0' to be used as well.

examples/src/ExampleInstrumentation.php, src/API/Configuration/ConfigProperties.php, src/API/Configuration/ConfigProviderInterface.php, src/API/Configuration/Noop/NoopConfigProperties.php, src/API/Configuration/Noop/NoopConfigProvider.php, src/API/Instrumentation/AutoInstrumentation/ConfigurationRegistry.php, src/API/Instrumentation/AutoInstrumentation/Instrumentation.php, src/SDK/SdkAutoloader.php, src/SDK/composer.json, tests/Unit/API/Configuration/Noop/NoopConfigPropertiesTest.php, tests/Unit/API/Configuration/Noop/NoopConfigProviderTest.php, tests/Unit/API/Instrumentation/AutoInstrumentation/ExtensionHookManagerTest.php, tests/Unit/API/Instrumentation/AutoInstrumentation/LateBindingProviderTest.php
implement recent additions to the otel spec re: config provider. Config provider should return a ConfigProperties, but we were already returning a ConfigurationRegistry. Added a ConfigProperties interface for ConfigurationRegistry to implement, which gets us pretty close to spec. We don't make ConfigProvider globally available, instead passing the ConfigurationRegistry in to each instrumentation as we register it. The spec allows for this.
=> adding config provider

script/semantic-conventions/README.md, script/semantic-conventions/templates/AttributeValues.php.j2, script/semantic-conventions/templates/trace_values_deprecations.php.partial, src/SemConv/ResourceAttributeValues.php, src/SemConv/TraceAttributeValues.php
the MESSAGING_OPERATION_* attribute values were removed in semconv 1.26.0, so update our generation to put them back, marking as deprecated
=> re-adding removed trace attribute values

src/API/Instrumentation/SpanAttribute.php, src/API/Instrumentation/WithSpan.php, tests/Unit/API/Instrumentation/SpanAttributeTest.php, tests/Unit/API/Instrumentation/WithSpanTest.php
adding WithSpan and SpanAttribute attributes to the API. These attributes are used by an upcoming feature in auto-instrumentation which allows users to add attributes to their code to enable auto-instrumentation.
=> adding auto-instrumentation attribute to API

src/API/Instrumentation/WithSpanHandler.php, tests/Integration/SDK/Trace/test_auto_root_span_withspan_localrootspan.phpt, tests/Integration/SDK/Trace/test_withspan_instrumentation.phpt
- class is nullable for pre hooks
- add phpt tests for withspan and its interaction with auto root span
=> fix withspan handler nullable + example

examples/traces/demo/collector/config.yaml, files/collector/otel-collector-config.yml
This exporter has been replaced by the debug exporter and will be removed soon. Related to https://github.com/open-telemetry/opentelemetry-collector/pull/11037
=> fix: update references to logging exporter

examples/traces/demo/docker-compose.yml
Follow-up from #1383. Debug exporter isn't available ~until v0.86.0~ in v0.39.0 which is still listed in the one example app, so this new configuration throws an error when trying to run the collector. `Error: cannot unmarshal the configuration: unknown exporters type "debug" for "debug"`.
Instead of setting to ~v0.86.0~ a specific version, I noticed the other docker-compose files (e.g. [docker-compose.collector.yaml](https://github.com/open-telemetry/opentelemetry-php/blob/main/docker-compose.collector.yaml)) omitted the tag which looks to pull in latest. I just updated this to match.
edited description: I'm not positive what version "debug" became available, just doesn't seem to be 0.39 😄
=> fix: Update collector tag in example to latest

src/API/Metrics/LateBindingMeter.php, src/API/Metrics/MeterInterface.php, src/API/Metrics/Noop/NoopMeter.php, src/SDK/Metrics/Instrument.php, src/SDK/Metrics/Meter.php, src/SDK/Metrics/MeterInstruments.php, src/SDK/Metrics/MeterProvider.php, src/SDK/Metrics/MetricFactory/StreamMetricSource.php, src/SDK/Metrics/MetricReader/ExportingReader.php, src/SDK/Metrics/MetricRegistry/MetricRegistry.php, src/SDK/Metrics/MetricRegistry/MetricRegistryInterface.php, src/SDK/Metrics/MetricSourceInterface.php, src/SDK/Metrics/MetricSourceRegistryUnregisterInterface.php, src/SDK/Metrics/ObservableInstrumentTrait.php, src/SDK/Metrics/RegisteredInstrument.php, src/SDK/Metrics/SynchronousInstrumentTrait.php, tests/Integration/SDK/Metrics/MeterConfigTest.php, tests/Unit/SDK/Metrics/InstrumentTest.php, tests/Unit/SDK/Metrics/MeterProviderTest.php, tests/Unit/SDK/Metrics/MeterTest.php, tests/Unit/SDK/Metrics/MetricReader/ExportingReaderTest.php, tests/Unit/SDK/Metrics/View/SelectionCriteriaTest.php
Removes `MeterInterface::isEnabled()` as it is not part of the spec, metrics API uses `Instrument::isEnabled()` instead.
Also resolves https://github.com/open-telemetry/opentelemetry-php/pull/1353#discussion_r1688754362 by dropping/recreating metric streams on configuration change.
=> Remove `MeterInterface::isEnabled()` and recreate metric streams on config re-enabling

composer.json, src/Config/SDK/composer.json, src/SDK/composer.json
Move to v1 of SPI package, which includes some nice-to-have changes for pre-registering instrumentation outside of runtime.
=> Update SPI dependency.

.gitignore, DEVELOPMENT.md, Makefile, docker-compose.phpDocumentor.yaml, phpdoc.dist.xml
fixes #1378:
* Introduce 2 new instructions in the Makefile to generate API documentation and to preview the documentation
* Adds a docker compose file that provides the runner and preview service
* Add a basic configuration file for phpdoc
* Add instructions to DEVELOPMENT.md on how to use these additional commands
=> add phpDocumentor instructions to Makefile

tests/Unit/SDK/Common/Http/Psr/Message/UsesRequestFactoryTrait.php, tests/Unit/SDK/Common/Http/Psr/Message/UsesServerRequestFactoryTrait.php
PSR7 `RequestInterface::getUri()` must return `UriInterface`, not `string`; explicit typehint was added in `2.0`.
See https://github.com/open-telemetry/opentelemetry-php/actions/runs/11087368795/job/30806007374?pr=1391#step:17:50.
=> Fix `IncompatibleReturnValueException` in `MessageFactoryTest`

src/API/Instrumentation/AutoInstrumentation/HookManagerInterface.php
Align OpenTelemetry\API\Instrumentation\AutoInstrumentation\HookManagerInterface::hook postHook Closure signature with OpenTelemetry\Instrumentation\hook.
Phan complains in open-telemetry/opentelemetry-php-contrib#269. Upon checking, I think the annotated signature of the post-hook is possibly incorrect?
This is an example of what I am seeing:.
In pre-hook:
```
src/Hooks/Illuminate/Contracts/Http/Kernel.php:48 PhanTypeMismatchArgumentSuperType Argument 3 ($preHook) is (function) of type Closure(\Illuminate\Contracts\Http\Kernel,array,string,string,?string,?int):array{0:?\Illuminate\Http\Request} but \OpenTelemetry\API\Instrumentation\AutoInstrumentation\HookManagerInterface::hook() takes Closure(null|object|string,array,string,string,null|string,int|null):void|null defined at …
```
=> Fix HookManagerInterface annotation 

src/API/composer.json
Makes extension hook manager available via SPI even if SDK is not installed.
Not removing registration in SDK to not break API 1.1.0 w/ SDK >1.1.0.
=> Move hook manager registration to API package

src/SDK/Resource/Detectors/Host.php, tests/Unit/SDK/Resource/Detectors/HostTest.php
Check if files are readable before trying to read them. Also check whether `kenv` exists before executing it, since it complains when I run it locally on a non-BSD system.
Closes: #1397
=> check for readable host id files before read

examples/instrumentation/configure_instrumentation.php, src/API/Instrumentation/AutoInstrumentation/Context.php, src/SDK/Propagation/LateBindingTextMapPropagator.php, src/SDK/SdkAutoloader.php, tests/Unit/API/Instrumentation/AutoInstrumentation/ContextTest.php, tests/Unit/API/Instrumentation/AutoInstrumentation/LateBindingProviderTest.php
Necessary for HTTP instrumentations etc.
=> Add `TextMapPropagator` to instrumentation context

src/Contrib/Zipkin/SpanConverter.php, tests/Unit/Contrib/Zipkin/ZipkinSpanConverterTest.php
=> ensure zipkin tags and attributes are cast to strings

src/SDK/Trace/AutoRootSpan.php
**Problem:** The start time in `AutoRootSpan` is recorded in milliseconds instead of nanoseconds.
**Proposal:** Use `ClockInterface::NANOS_PER_SECOND` instead of a magic value.
=> Fix start timestamp in auto root span

.github/workflows/phpdoc-to-github-pages
Follow-up to #1378 and #1385:
I did some investigation how to best publish the API documentation for PHP. Initially I was hoping that we can serve these pages through netlify (the service we use to publish opentelemetry.io), unfrotunately I ran into some limitations in my experiment, that I could not resolve, see: https://github.com/open-telemetry/opentelemetry.io/pull/5413
Therefore I suggest to publish the pages to github via the workflow in this PR. This will create a page similar to
https://svrnm.github.io/opentelemetry-php/
(it will then be named https://open-telemetry.github.io/opentelemetry-php/)
We can then link this page from the website here: https://opentelemetry.io/docs/languages/#api-references and from within the navigation tree of the PHP language specific documentation. …
=> Workflow to publish phpdoc to github pages

proto/otel/composer.json
If google protobuf v4 is not allowed, the package version 1.0.0beta5 will be installed, which breaks the application.
The same value is in the root composer.json:
https://github.com/open-telemetry/opentelemetry-php/blob/1aae9dd61930ac02d2936e1eda795c39c4f7a959/composer.json#L11
=> Support google protobuf v4

src/SDK/Resource/Detectors/Host.php
There's other circumstances besides is_file && is_readable when file_get_contents may return false. This is a defensive change to prevent TypeErrors when calling trim()
=> guard against possible false value from file_get_contents in Host.php

src/API/Instrumentation/SpanAttribute.php, tests/Unit/API/Instrumentation/SpanAttributeTest.php
Fixes #1429
Although the added "test" might not be appropriate. Is there a better way to test this?
It just proves that phpstan is happy rather than asserting anything more concrete.
=> Added \Attribute::TARGET_PARAMETER to \OpenTelemetry\API\Instrumentation\SpanAttribute

examples/load_config.yaml, examples/load_config_env.yaml, src/Config/SDK/ComponentProvider/Logs/LogRecordExporterOtlp.php, src/Config/SDK/ComponentProvider/Metrics/MetricExporterOtlp.php, src/Config/SDK/ComponentProvider/OpenTelemetrySdk.php, src/Config/SDK/ComponentProvider/Trace/SpanExporterOtlp.php, src/SDK/Metrics/Stream/DeltaStorage.php, tests/Integration/Config/configurations/anchors.yaml, tests/Integration/Config/configurations/kitchen-sink.yaml
- headers and attributes are now arrays with `key` and `value` elements
- headers can optionally contain a `headers_list` element which supports a lower-priority CSV of key/value entries
- attributes can optionally contain an `attributes_list` element which supports a lower-priority CSV of key/value entries
Related: #1423
=> add sdk-config 0.3 support for key/value headers and attributes

src/SDK/Resource/Detectors/Host.php, tests/Integration/SDK/Resource/Detectors/test_host_detector_with_open_basedir.phpt
if `open_basedir` is configured such that files that the host detector tries to open are denied with a php warning, and a custom error handler is installed which converts warnings to exceptions, an unhandled exception occurs.
add a test for this, and some try/catch/ignore blocks around the code that can trigger this.
Closes: #1450
Replace: #1451
=> handle host detector with custom error handler and open_basedir

src/API/Globals.php, src/API/Instrumentation/CachedInstrumentation.php, src/API/Instrumentation/Configurator.php, src/API/Instrumentation/ContextKeys.php, src/API/Logs/EventLoggerInterface.php, src/API/Logs/EventLoggerProviderInterface.php, src/API/Logs/NoopEventLogger.php, src/API/Logs/NoopEventLoggerProvider.php, src/SDK/Logs/EventLogger.php, src/SDK/Logs/EventLoggerProvider.php, src/SDK/Logs/EventLoggerProviderFactory.php, src/SDK/Logs/EventLoggerProviderInterface.php, src/SDK/Logs/NoopEventLoggerProvider.php, src/SDK/Sdk.php, src/SDK/SdkAutoloader.php, src/SDK/SdkBuilder.php
The event logger was a Development-status component of the logging signal. It has been removed in favour of adding emitEvent to the logger interface, see https://github.com/open-telemetry/opentelemetry-specification/pull/4319
Related: #1459
=> deprecate event logger

src/SDK/Common/Configuration/Defaults.php, src/SDK/Common/Configuration/KnownValues.php, src/SDK/Resource/ResourceInfoFactory.php, tests/Integration/SDK/Resource/ResourceInfoFactoryTest.php, tests/Unit/SDK/Resource/ResourceInfoFactoryTest.php
Limit the default detectors from everything to:
- sdk
- sdk_provided
- env
This is controlled by a new detector key, OTEL_PHP_DETECTORS=default (which is the default if no value is provided). The previous behaviour can be restored by explicitly setting OTEL_PHP_DETECTORS=all.
Closes: #1320
=> reduce default set of resource detectors

composer.json, src/Config/SDK/ComponentProvider/Logs/LogRecordExporterOtlpFile.php, src/Config/SDK/ComponentProvider/Metrics/MetricExporterOtlpFile.php, src/Config/SDK/ComponentProvider/OutputStreamParser.php, src/Config/SDK/ComponentProvider/Trace/SpanExporterOtlpFile.php, src/Config/SDK/composer.json, tests/Integration/Config/ConfigurationTest.php, tests/Integration/Config/configurations/kitchen-sink.yaml, tests/Unit/Config/SDK/ComponentProvider/OutputStreamParserTest.php
the spec has added in-development otlp file/stdout exporter. We already supported this programmatically, so
add some factories and sdk config to allow configuration from environment (only for stdout, per spec)
=> adding otlp/file exporter

src/API/Logs/LogRecord.php, src/SDK/Logs/Exporter/InMemoryExporter.php, src/SDK/Logs/LogRecordProcessorInterface.php, src/SDK/Logs/Processor/BatchLogRecordProcessor.php, src/SDK/Logs/Processor/MultiLogRecordProcessor.php, src/SDK/Logs/Processor/NoopLogRecordProcessor.php, src/SDK/Logs/Processor/SimpleLogRecordProcessor.php, src/SDK/Logs/ReadWriteLogRecord.php, src/SDK/Logs/ReadableLogRecord.php, tests/Integration/SDK/Logs/LoggerTest.php, tests/Unit/SDK/Logs/ReadWriteLogRecordTest.php
https://github.com/open-telemetry/opentelemetry-specification/pull/3907 implements some new requirements for logging:
- ReadWriteLogRecord can mutate (eg by processors)
- mutated ReadWriteLogRecord can be seen by later processors
This is a breaking change because LogRecordProcessorInterface onEmit param changes to by-reference
=> implement mutable ReadWriteLogRecord

src/Config/SDK/Configuration/Internal/EnvSubstitutionNormalization.php, tests/Unit/Config/SDK/Configuration/ConfigurationFactoryTest.php
Updating env var substitution to conform to https://github.com/open-telemetry/opentelemetry-specification/blob/v1.41.0/specification/configuration/data-model.md#environment-variable-substitution
- `env:` prefix allowed in environment variable
- do not recursively apply env var substitution (ie don't allow env vars in env vars)
=> yaml config env var spec conformance

src/API/Baggage/BaggageBuilder.php, tests/Unit/API/Baggage/BaggageTest.php
spec 1.36.0 clarifies that empty string is not a valid baggage name
see https://github.com/open-telemetry/opentelemetry-specification/pull/4144
=> disallow empty string for baggage name

src/SDK/Logs/LogRecordProcessorInterface.php, src/SDK/Logs/Processor/BatchLogRecordProcessor.php, src/SDK/Logs/Processor/MultiLogRecordProcessor.php, src/SDK/Logs/Processor/NoopLogRecordProcessor.php, src/SDK/Logs/Processor/SimpleLogRecordProcessor.php, tests/Integration/SDK/Logs/LoggerTest.php, tests/Integration/SDK/Logs/test_mutate_log_record_in_onemit.phpt
add a test to demonstrate that mutations are still seen by later processors without by-reference
=> revert pass-by-reference to LogRecordProcessor::onEmit

src/SDK/Metrics/Meter.php, tests/Unit/SDK/Metrics/MeterTest.php
if no observers are registered for a meter's instruments, some tests were emitting php warnings:
- foreach() argument must be of type array|object, null given
- Undefined array key XXX
null coalesce to an empty array to make the test happy.
=> handle empty meter observers

src/API/Common/Time/ClockInterface.php, src/Contrib/Grpc/GrpcTransport.php, src/Contrib/Grpc/GrpcTransportFactory.php, tests/Unit/Contrib/Grpc/GrpcTransportTest.php
Fixes #1498 (grpc timeouts not being respected)
The timeout seems to work correctly for long and short variants of the bug with this code but  I wasn't able to create meaningful tests.  Whilst it was possible to get the calculated timeval from the transport instance using reflection,  actually calling functions on `\Grpc\Timeval` (such as [similar()](https://grpc.github.io/grpc/php/class_grpc_1_1_timeval.html#a6bc3609d25c19f9297749781efd1071e) just crashes the test runner
No additional unit tests fail compared to `main` (35 vs 35)
Happy to make any adjustments according to feedback
=> fix gRPC timeout (#1498)

src/Contrib/Grpc/GrpcTransportFactory.php
Fixes a couple of style issues from #1499
=> A couple of code tidies left over from PR #1499

script/semantic-conventions/semconv.sh, src/SemConv/ResourceAttributeValues.php, src/SemConv/ResourceAttributes.php, src/SemConv/TraceAttributeValues.php, src/SemConv/TraceAttributes.php, src/SemConv/Version.php, src/SemConv/composer.json
generate semantic conventions 1.30 (NB that 1.29 contained a bug, and the recommendation is to skip it).
support php 8.0, since it still works against this version and we have a bunch of auto-instrumentation packages that support 8.0
=> Semconv 1.30

src/Contrib/Grpc/GrpcTransport.php, src/Contrib/Grpc/GrpcTransportFactory.php
using a newly-added const in ClockInterface breaks things for some older PHP versions, so lets use a local const for now
=> use a local const for grpc time conversions

docs/upgrading.md, src/Contrib/Otlp/MetricExporter.php, src/Contrib/Otlp/MetricExporterFactory.php, src/SDK/Metrics/AggregationInterface.php, src/SDK/Metrics/AggregationTemporalitySelectorInterface.php, src/SDK/Metrics/Data/Histogram.php, src/SDK/Metrics/Data/Sum.php, src/SDK/Metrics/Data/Temporality.php, src/SDK/Metrics/DefaultAggregationProviderInterface.php, src/SDK/Metrics/DefaultAggregationProviderTrait.php, src/SDK/Metrics/Instrument.php, src/SDK/Metrics/InstrumentType.php, src/SDK/Metrics/Meter.php, src/SDK/Metrics/MetricExporter/ConsoleMetricExporter.php, src/SDK/Metrics/MetricExporter/InMemoryExporter.php, src/SDK/Metrics/MetricFactory/StreamMetricSourceProvider.php, src/SDK/Metrics/MetricMetadataInterface.php, src/SDK/Metrics/MetricReader/ExportingReader.php, src/SDK/Metrics/MetricSourceProviderInterface.php, src/SDK/Metrics/Stream/AsynchronousMetricStream.php, src/SDK/Metrics/Stream/MetricStreamInterface.php, src/SDK/Metrics/Stream/SynchronousMetricStream.php, src/SDK/Metrics/View/SelectionCriteria/InstrumentTypeCriteria.php, tests/Unit/Contrib/Otlp/MetricExporterFactoryTest.php, tests/Unit/SDK/Metrics/MetricReader/ExportingReaderTest.php, tests/Unit/SDK/Metrics/View/SelectionCriteriaTest.php
Remove forwards-compatible Metrics features for 2.x:
- No longer accept strings for Temporality and InstrumentType
- `$advisory` added to `DefaultAggregationProviderInterface`
=> drop string options for Temporality, InstrumentType

src/API/Metrics/LateBindingMeter.php, tests/Unit/API/Instrumentation/AutoInstrumentation/LateBindingProviderTest.php
```
NoopMeter::createObservableUpDownCounter(): Argument #5 must be of type callable, array given
#0 NoopMeter->createObservableUpDownCounter('php.memory.usag...', 'By', 'The amount of p...', Array, Array)
#1 LateBindingMeter->createObservableUpDownCounter('php.memory.usag...', 'By', 'The amount of p...', _: Object(Closure))
```
=> Fix type error when using `LateBindingMeter::createObservable{Instrument}()`

src/Config/SDK/Configuration/Loader/YamlSymfonyFileLoader.php
Fixes a minor bug that did not affect our use-case.
We were passing the relative path `$resource` instead of the absolute path `$path` that was returned by the locator (in our case always resolved relative to `getcwd()` -> no impact) to `Yaml::parseFile()`.
=> Fix `YamlSymfonyFileLoader` if locator uses directory besides `getcwd()`

.github/workflows/publish-otel-php-base-docker-image.yml, docker/Dockerfile
This changes how images are built. In order to be a little more deterministic, we use set versions in `Dockerfile`.
This, in conjunction with #1544 , will make for a more ordered dependency updates.
=> chore: build images dynamically

.github/workflows/publish-otel-php-base-docker-image.yml
Bumps the timeout to 500 (default 360) minutes.
=> fix: bump timeout for building images

tests/Unit/Context/ScopeTest.php
this test triggers a bug that surfaced in xdebug 3.4.2, see https://bugs.xdebug.org/view.php?id=2332
Related issue: #1554
=> skip segfault-inducing test

src/SDK/Common/Attribute/Attributes.php
This PR fixes a case that when using console exporter for metrics, attributes are not included in the export
Without fix:
```json
{
"name": "http.client.request.body.size",
"description": null,
"unit": "By",
"data": {
"dataPoints": [
{
"count": 1,
"sum": 14,
"min": 14,
"max": 14,
"bucketCounts": [
0,
0,
0,
1,
0,
0,
0,
0,
0,
0,
0
],
"explicitBounds": [
0,
5,
10,
25,
50,
75,
100,
250,
500,
1000
],
"attributes": {},
"startTimestamp": 1744027586704128264,
"timestamp": 1744027586707302423,
"exemplars": [
{
"value": 14,
"timestamp": 1744027586707167890,
"attributes": {},
"traceId": "036ad4d4fb29b907001b2927da026772",
"spanId": "bfb17e41639c4a12"
}
]
}
],
"temporality": "Delta"
}
}
```
with fix:
```json
{
"name": "http.client.request.body.size",
"description": null,
"unit": "By",
"data": { …
```
=> Fix missing metrics attributes in console exporter

src/SDK/Common/Export/InMemoryStorageManager.php, src/SDK/Logs/Exporter/InMemoryExporterFactory.php, src/SDK/Metrics/MetricExporter/InMemoryExporter.php, src/SDK/Metrics/MetricExporter/InMemoryExporterFactory.php, src/SDK/Trace/SpanExporter/InMemorySpanExporterFactory.php, tests/Integration/SDK/Common/InMemoryStorageManagerWithSKDAutoload.php, tests/Integration/SDK/Metrics/MeterConfigTest.php, tests/Unit/SDK/Common/Export/InMemoryStorageManagerTest.php, tests/Unit/SDK/Metrics/MetricReader/ExportingReaderTest.php
Introduced `InMemoryStorageManager` to centralize storage management for spans, metrics, and logs. Updated InMemory exporters and their factory classes to utilize this shared storage.
=> Refactor InMemory exporters to use shared storage manager

src/SDK/Common/Http/Psr/Client/Discovery/Symfony.php
Closes: https://github.com/open-telemetry/opentelemetry-php/issues/1574
=> Use timeout to set max_duration on symfony http client

src/Context/Propagation/ArrayAccessGetterSetter.php, src/Context/Propagation/ExtendedPropagationGetterInterface.php, src/Context/Propagation/PropagationGetterInterface.php, src/Context/Propagation/SanitizeCombinedHeadersPropagationGetter.php, tests/Unit/Context/Propagation/ArrayAccessGetterSetterTest.php, tests/Unit/Context/Propagation/SanitizeCombinedHeadersPropagationGetterTest.php
=> implement getAll function in TextMap Extract

script/semantic-conventions/semconv.sh, script/semantic-conventions/templates/registry/php/weaver.yaml, src/SemConv/ResourceAttributeValues.php, src/SemConv/ResourceAttributes.php, src/SemConv/TraceAttributeValues.php, src/SemConv/TraceAttributes.php, src/SemConv/Version.php, tests/Integration/Config/configurations/kitchen-sink.yaml
Generate latest SemConv via weaver. In passing, remove a couple of namespaces that don't seem appropriate for PHP: cpython, ios, android.
Closes: #1541
=> Semconv 1.32.0

src/API/Logs/LateBindingLogger.php, src/API/Logs/LogRecord.php, src/API/Logs/LoggerInterface.php, src/API/Logs/NoopLogger.php, src/Contrib/Otlp/LogsConverter.php, src/SDK/Logs/Logger.php, src/SDK/Logs/ReadableLogRecord.php
- update Logger.isEnabled signature to include context and severity number, per spec
- remove experimental tag from isEnabled
- accept event_name on a LogRecord
- add event name to otlp logs payload
- update or remove some comments that were based on the old logs-bridge specification
Closes: #1563
=> stabilize logger.enabled

src/Context/ContextStorageNode.php, tests/Unit/Context/ScopeTest.php
Use dummy object instead of self references as detached-marker to avoid relying on gc cycle collection.
Resolves #1584.
=> Allow immediate gc of `ContextStorageNode`s after `::detach()`

docker/Dockerfile
Dependabot opened a PR here: https://github.com/open-telemetry/opentelemetry-php/pull/1588 that inadvertently updated all of the versions of PHP in our docker file to `php:8.4.7-cli-alpine`.
That was incorrect, but was the inspiration for this PR -  which ensures each version of php is the latest for its particular release.
=> chore: update docker container versions

src/Contrib/Otlp/ProtobufSerializer.php
Resolves #1597 by ignoring the `TypeError`; could alternatively check for installed extension version but this fix seems simpler.
=> Ignore `TypeError` in `::serializeToJsonString()` if `google/protobuf` `^4.31` and `ext-protobuf` `<4.31` are installed

src/Contrib/Otlp/OtlpHttpTransportFactory.php, src/SDK/Common/Export/Http/PsrTransportFactory.php
I don't know if this is considered a breaking change or not, but it fixes an issue I raised.
Fixes: #1600
=> Fixes #1600

src/SDK/Trace/Sampler/TraceIdRatioBasedSampler.php, tests/Integration/SDK/TraceIdRatioBasedSamplerTest.php, tests/Unit/SDK/Trace/Sampler/TraceIdRatioBasedSamplerTest.php
Computes the sampling threshold as defined in https://github.com/open-telemetry/opentelemetry-specification/pull/4166 / [Converting floating-point probability to threshold value](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/tracestate-probability-sampling.md#converting-floating-point-probability-to-threshold-value) / [TraceIdRatioBased sampler algorithm
](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#traceidratiobased-sampler-algorithm)
This PR does not implement tracestate handling (`rv` value is not read / `th` is not set), it only updates the algorithm to calculate the 56-bit rejection threshold according to the spec.
=> Update `TraceIdRatioBasedSampler` to calculate sampling threshold according to OTEP 235

tests/Unit/Context/ScopeTest.php
verified that the bug we experience still exists in xdebug 3.4.4 so lets assume it will be live for some more releases, and un-skip the test in the future
=> skip segfaulting test on more xdebug versions

src/API/Logs/LateBindingLogger.php, src/API/Logs/LoggerInterface.php, src/API/Logs/NoopLogger.php, src/SDK/Logs/LogRecordProcessorInterface.php, src/SDK/Logs/Logger.php
extra parameter, "event name", added in spec 1.45.0 which is optional and development stability
see https://github.com/open-telemetry/opentelemetry-specification/blob/v1.45.0/specification/logs/api.md#enabled
I've left LogRecordProcessor.enabled as a todo, as we're not using it and it would require another interface to avoid BC break (plus, we're not using it and it's not marked stable)
=> add Logger.Enabled event name parameter

examples/baggage/baggage_with_environment_carrier.php, examples/traces/features/context_with_environment_carrier.php, src/Context/Propagation/EnvironmentGetterSetter.php, tests/Unit/Context/Propagation/EnvironmentGetterSetterTest.php
=> feat(carreirs): implement environment context getter setter

files/collector/otel-collector-config.yml
by default, the collector only listens on localhost now, and so is not reachable from dev containers when running examples
=> update collector to listen on all interfaces

src/SDK/composer.json
Currently `open-telemetry/sdk` locks `open-telemetry/api` at `1.4.0` and does not allow upgrades to `1.5.0` due to incorrect version constraint. Fixes #1706 
```
Problem 1
- Root composer.json requires open-telemetry/sdk ^1.7 -> satisfiable by open-telemetry/sdk[1.7.0].
- open-telemetry/sdk 1.7.0 requires open-telemetry/api ~1.4.0 -> found open-telemetry/api[1.4.0] but the package is fixed to 1.5.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
Problem 2
- open-telemetry/exporter-otlp is locked to version 1.3.2 and an update of this package was not requested.
- open-telemetry/exporter-otlp 1.3.2 requires open-telemetry/sdk ^1.0 -> satisfiable by open-telemetry/sdk[1.7.0].
- open-telemetry/sdk 1.7.0 …
```
=> Allow installing SDK with API v1.5
